// CloudNativePG index cards.
//
// One deck per technology; this is the CNPG one. Each card is a single question and a short
// answer, drawn from the two places the labs' knowledge already lives: the Command Reference
// (`src/reference/cnpg.js`) and the lecture notes on each lab's detail page
// (`catalog.json`'s `lectureNotes`). See CLAUDE.md, "Index card contract".
//
// The rule that keeps these honest is the same one that governs the reference: nothing here
// is invented. Every fact on a `back` was observed in a real run against a real k3d +
// CloudNativePG cluster, or is the plain reading of a spec field the labs actually set. A
// card is a *recall prompt*, not a summary — if the answer needs a paragraph, it belongs in
// the reference or the lecture notes and the card should ask a narrower question.

export const cnpgCards = {
  id: 'cnpg',
  title: 'CloudNativePG',
  blurb: 'Recall prompts for the commands and the concepts the CloudNativePG labs teach.',
  intro: `Each card asks one question and answers it in a line or two. They come from the same material as the **Command Reference** and the labs' lecture notes, compressed to the point where you can test yourself rather than read.

Cards tagged *command* come from the Command Reference and are about what to type and what comes back; cards tagged *lecture* come from the labs' lecture notes and are about why the system behaves as it does. Both carry the labs they came from, so a card you cannot answer leads straight back to the lab that teaches it.

Nothing here is illustrative. Every behaviour a card asserts was observed in a real run against a real cluster.`,

  groups: [
    {
      id: 'survey',
      title: 'Surveying a cluster',
      blurb: 'The handful of reads every lab opens with.',
      cards: [
        {
          id: 'who-is-primary',
          kind: 'command',
          front: 'How do you ask a CloudNativePG cluster which instance is primary right now?',
          back: '`kubectl get cluster pg-cluster -o jsonpath=\'{.status.currentPrimary}\'`. Ask, never assume — it changes on every failover and switchover.',
          usedIn: ['cnpg-failover', 'cnpg-switchover'],
        },
        {
          id: 'cluster-healthy-phrase',
          kind: 'command',
          front: 'What exact phrase does a healthy Cluster report in `.status.phase`?',
          back: '`Cluster in healthy state`. Anything else — "Creating a new replica", "Waiting for the instances to become active" — means work is in progress.',
          usedIn: ['cnpg-cluster-creation'],
        },
        {
          id: 'running-image-vs-spec',
          kind: 'lecture',
          front: 'Why read a Pod\'s image from `.status.containerStatuses[0].image` rather than its spec?',
          back: 'The spec is what it was asked to run; the status is what it is running. During a rolling update they differ, which is exactly when you need to know.',
          usedIn: ['cnpg-rolling-update'],
        },
        {
          id: 'cnpg-status',
          kind: 'command',
          front: 'Which single command summarises a whole cluster — primary, instances, WAL position, replication?',
          back: '`kubectl cnpg status pg-cluster`, from the cnpg kubectl plugin.',
          usedIn: ['cnpg-switchover', 'cnpg-fencing'],
        },
      ],
    },

    {
      id: 'operator',
      title: 'The operator',
      blurb: 'Installing it, upgrading it, and what happens when it is not there.',
      cards: [
        {
          id: 'server-side-apply',
          kind: 'command',
          front: 'Why must the CloudNativePG operator manifest be applied with `--server-side`?',
          back: 'Its CRDs are far larger than the 256 KB limit on a client-side apply\'s last-applied annotation, so a plain `kubectl apply` fails outright.',
          usedIn: ['cnpg-operator-install', 'cnpg-operator-upgrade'],
        },
        {
          id: 'operator-upgrade-instances',
          kind: 'lecture',
          front: 'What happens to running PostgreSQL instances when you upgrade the operator?',
          back: 'Nothing. Pod ages keep climbing and restart counts stay at 0 — the operator is not on the data path, which is what makes a minor upgrade routine.',
          usedIn: ['cnpg-operator-upgrade'],
        },
        {
          id: 'operator-scaled-to-zero',
          kind: 'lecture',
          front: 'The operator is scaled to zero. What breaks first?',
          back: 'Creating or changing a Cluster: the admission webhook has no endpoints, so the API server refuses the request. Existing databases keep serving.',
          usedIn: ['cnpg-operator-deployment'],
        },
        {
          id: 'operator-ha-lease',
          kind: 'lecture',
          front: 'Three operator replicas are running. How many are doing work, and what decides which?',
          back: 'One. Leader election through a Lease; the others stand by. Deleting the holder saw a standby take over in about 2 seconds, because a clean shutdown releases the Lease rather than letting it expire.',
          usedIn: ['cnpg-operator-ha'],
        },
        {
          id: 'operator-eviction-pdb',
          kind: 'lecture',
          front: 'Why can a single-replica operator with a `minAvailable: 1` PodDisruptionBudget hang a node drain?',
          back: 'The Eviction API returns `TooManyRequests` forever — the budget can never be satisfied by evicting the only replica. A second replica resolves it.',
          usedIn: ['cnpg-operator-eviction'],
        },
        {
          id: 'operator-config-absent',
          kind: 'lecture',
          front: 'What operator-wide configuration does a default installation actually have?',
          back: 'None. It starts with `--config-map-name=cnpg-controller-manager-config` and a matching secret name, and neither object exists until someone creates it.',
          usedIn: ['cnpg-operator-configmap'],
        },
        {
          id: 'operator-config-startup',
          kind: 'lecture',
          front: 'You edit the operator ConfigMap. When does the change take effect?',
          back: 'Not until the operator restarts — it is read once, at startup. Editing it and waiting achieves nothing.',
          usedIn: ['cnpg-operator-configmap'],
        },
        {
          id: 'operator-pod-deleted',
          kind: 'lecture',
          front: 'You delete the operator Pod. What happens to queries in flight?',
          back: 'Nothing — the operator is not on the data path. The Deployment replaces the Pod, the new process takes the leader-election Lease, and reconciliation resumes while the database never pauses.',
          usedIn: ['cnpg-operator-pod-deletion'],
        },
        {
          id: 'operator-zero-consequence',
          kind: 'lecture',
          front: 'With the operator scaled to zero, you delete an instance Pod. What happens?',
          back: 'Nothing replaces it. The cluster keeps serving on the instances that remain — what you lose with the operator is reconciliation, not availability.',
          usedIn: ['cnpg-operator-pod-deletion', 'cnpg-operator-deployment'],
        },
        {
          id: 'image-catalog-schema',
          kind: 'command',
          front: 'An ImageCatalog is rejected with a strict-decoding error. What is the likely mistake?',
          back: '`major` put under `spec.componentImages`. `spec.images` is the required list and takes `{major, image}`; `componentImages` is a separate list keyed by `{key, image}` for non-PostgreSQL components.',
          usedIn: ['cnpg-image-catalog'],
        },
        {
          id: 'image-catalog-swap',
          kind: 'command',
          front: 'Why must removing `spec.imageName` and adding `imageCatalogRef` be a single patch?',
          back: 'A Cluster may name an image or reference a catalog, never both — so the remove and the add go in one atomic JSON patch rather than two steps.',
          usedIn: ['cnpg-image-catalog'],
        },
        {
          id: 'image-catalog-lever',
          kind: 'lecture',
          front: 'What does referencing a catalog buy over naming the image directly?',
          back: 'The upgrade lever moves off the Cluster. Editing the catalog rolls every cluster referencing it, and those clusters cannot drift from it because they have no image of their own.',
          usedIn: ['cnpg-image-catalog'],
        },
      ],
    },

    {
      id: 'cluster',
      title: 'Clusters and storage',
      blurb: 'Instances, volumes, and what scaling actually creates and destroys.',
      cards: [
        {
          id: 'scale-up-objects',
          kind: 'lecture',
          front: 'You change `spec.instances` from 3 to 4. What does the operator create?',
          back: 'A PersistentVolumeClaim, a short-lived `*-join-*` Pod running `pg_basebackup` against the primary, a replication slot, and the instance itself.',
          usedIn: ['cnpg-cluster-scaling'],
        },
        {
          id: 'scale-down-removes',
          kind: 'lecture',
          front: 'Scaling down removes an instance. What else goes with it, and which instance is chosen?',
          back: 'Its PVC *and* its replication slot, both deleted rather than orphaned. Always the highest-numbered instance — you do not get to choose.',
          usedIn: ['cnpg-cluster-scaling'],
        },
        {
          id: 'orphan-slot-danger',
          kind: 'lecture',
          front: 'Why is a replication slot left behind for a removed instance dangerous?',
          back: 'The primary reserves WAL for it forever. The first symptom is a full volume, which looks nothing like a replication problem.',
          usedIn: ['cnpg-cluster-scaling', 'cnpg-replication-slots'],
        },
        {
          id: 'new-replica-clone',
          kind: 'lecture',
          front: 'Why does a newly added instance already hold rows written before it existed?',
          back: 'It is cloned from the primary with `pg_basebackup`, not replayed from empty. The cost of scaling up is copying the data directory, not replaying history.',
          usedIn: ['cnpg-cluster-scaling'],
        },
        {
          id: 'pvc-per-instance',
          kind: 'lecture',
          front: 'How many PersistentVolumeClaims does a 3-instance cluster have, and what are they called?',
          back: 'One per instance Pod, named identically to it — `pg-cluster-1`, `-2`, `-3` — created automatically, with no PVC in the manifest.',
          usedIn: ['cnpg-persistent-volume'],
        },
        {
          id: 'local-path-pinning',
          kind: 'lecture',
          front: 'Why can a `local-path` volume never move to another node?',
          back: 'It provisions a hostPath directory on the node the Pod first scheduled to, recorded on the claim as `volume.kubernetes.io/selected-node`. Unlike a cloud CSI volume it cannot reattach anywhere else.',
          usedIn: ['cnpg-persistent-volume'],
        },
        {
          id: 'bootstrap-is-one-shot',
          kind: 'lecture',
          front: 'You patch `spec.bootstrap.initdb.database` on a running cluster. What happens?',
          back: 'It is accepted with no warning and has no effect. `bootstrap` is a one-shot instruction carried out at creation, never consulted again — so the spec permanently describes a database that does not exist.',
          usedIn: ['cnpg-initdb'],
        },
        {
          id: 'initdb-two-hooks',
          kind: 'command',
          front: 'What is the difference between `postInitSQL` and `postInitApplicationSQL`?',
          back: 'Which database they run in. `postInitSQL` runs in `postgres` as superuser; `postInitApplicationSQL` runs inside the application database. A `CREATE TABLE` in the wrong one lands somewhere nobody wants it.',
          usedIn: ['cnpg-initdb'],
        },
        {
          id: 'checksums-pg18-default',
          kind: 'lecture',
          front: '`data_checksums` is on in a cluster that never asked for it. Why?',
          back: "PostgreSQL 18's own initdb enables checksums by default. CloudNativePG's `dataChecksums` only controls whether `-k` is passed — on 18 the thing you would have to ask for is turning them off.",
          usedIn: ['cnpg-initdb'],
        },
        {
          id: 'initdb-permanent-choices',
          kind: 'lecture',
          front: 'Which initdb choices can never be changed without rebuilding the cluster?',
          back: 'The physical ones written into the data directory — WAL segment size, checksums, encoding and collation. Changing encoding or collation means a dump and restore into a new cluster, not a replica.',
          usedIn: ['cnpg-initdb'],
        },
      ],
    },

    {
      id: 'services',
      title: 'Services and connections',
      blurb: 'The three Services, and which one a client should be using.',
      cards: [
        {
          id: 'three-services',
          kind: 'lecture',
          front: 'A cluster gets `-rw`, `-ro` and `-r` Services. What is behind each?',
          back: '`-rw` the primary only; `-ro` the replicas only; `-r` every instance. Writes must use `-rw`, since only the primary accepts them.',
          usedIn: ['cnpg-service-connectivity'],
        },
        {
          id: 'app-secret',
          kind: 'command',
          front: 'Where do an application\'s credentials come from, and what type is that Secret?',
          back: 'The operator generates `<cluster>-app` of type `kubernetes.io/basic-auth`. It also carries the host, port, database name and ready-made connection URIs.',
          usedIn: ['cnpg-service-connectivity'],
        },
        {
          id: 'pgpassword-in-pod',
          kind: 'command',
          front: 'Why does `PGPASSWORD=$X kubectl exec pod -- psql …` fail to authenticate?',
          back: 'The variable is set on the kubectl client and never reaches the container. It has to be set *inside*: `kubectl exec pod -- env PGPASSWORD=$X psql …`.',
          usedIn: ['cnpg-service-connectivity'],
        },
      ],
    },

    {
      id: 'tls',
      title: 'TLS and certificates',
      blurb: 'What the cluster issues itself, and how to replace it with your own.',
      cards: [
        {
          id: 'cluster-is-a-ca',
          kind: 'lecture',
          front: 'What does a CloudNativePG cluster generate for itself on day one?',
          back: 'A CA, a server certificate and a client certificate for replication. `<cluster>-ca` holds `ca.crt` **and** `ca.key` — it is a working CA, not just a trust anchor.',
          usedIn: ['cnpg-client-certificates', 'cnpg-server-certificates'],
        },
        {
          id: 'connection-certificate',
          kind: 'command',
          front: 'How do you issue a client certificate for a PostgreSQL role, signed by the cluster\'s own CA?',
          back: '`kubectl cnpg certificate app-client-cert --cnpg-cluster pg-cluster --cnpg-user app`. The certificate\'s common name *is* the role name — that is the identity PostgreSQL reads.',
          usedIn: ['cnpg-client-certificates'],
        },
        {
          id: 'san-must-cover-services',
          kind: 'lecture',
          front: 'Your own server certificate names only `pg-cluster-rw`. What breaks, and when?',
          back: 'Every client connecting through another Service name, at connection time, under `verify-full` — which checks the host name dialled against the certificate.',
          usedIn: ['cnpg-server-certificates'],
        },
        {
          id: 'both-secrets-together',
          kind: 'lecture',
          front: 'Why must `serverCASecret` and `serverTLSSecret` be handed to the operator together?',
          back: 'Replicas verify the primary\'s certificate against the server CA. A new certificate without its CA stops replication, not just clients.',
          usedIn: ['cnpg-server-certificates'],
        },
        {
          id: 'starttls-postgres',
          kind: 'command',
          front: 'How do you see the certificate PostgreSQL actually presents on the wire?',
          back: '`openssl s_client -starttls postgres -connect pg-cluster-rw:5432`. `-starttls postgres` is required — TLS is negotiated through PostgreSQL\'s own handshake, not from the first byte.',
          usedIn: ['cnpg-server-certificates', 'cnpg-client-certificates'],
        },
        {
          id: 'sslmode-levels',
          kind: 'lecture',
          front: '`require`, `verify-ca`, `verify-full` — what does each actually check?',
          back: '`require` encrypts and verifies nothing; `verify-ca` checks the signature chain; `verify-full` also checks the host name dialled. Only the last detects an impostor.',
          usedIn: ['cnpg-client-certificates', 'cnpg-server-certificates'],
        },
      ],
    },

    {
      id: 'pooling',
      title: 'Connection pooling',
      blurb: 'PgBouncer as a declared resource.',
      cards: [
        {
          id: 'pooler-is-declared',
          kind: 'lecture',
          front: 'What does applying a `Pooler` resource produce?',
          back: 'A PgBouncer Deployment the operator builds and manages, with its own Service — plus Prometheus metrics on port 9127, without anyone asking.',
          usedIn: ['cnpg-pgbouncer', 'cnpg-pgbouncer-metrics'],
        },
        {
          id: 'pool-appears-with-traffic',
          kind: 'lecture',
          front: 'Why does a `cnpg_pgbouncer_pools_` series for your database not exist yet?',
          back: 'PgBouncer reports pools it has actually served, not pools it is configured to allow. An alert on a never-used pool never fires, because the series is absent.',
          usedIn: ['cnpg-pgbouncer-metrics'],
        },
      ],
    },

    {
      id: 'replication',
      title: 'Replication',
      blurb: 'Slots, synchronous commit, replica clusters and logical replication.',
      cards: [
        {
          id: 'ha-slots-default',
          kind: 'lecture',
          front: 'How many replication slots does a healthy 3-instance cluster hold, and who created them?',
          back: 'Two — one physical slot per replica, named `_cnpg_<instance>`. The operator, by default: high-availability slots are on with no configuration.',
          usedIn: ['cnpg-replication-slots'],
        },
        {
          id: 'what-a-slot-buys',
          kind: 'lecture',
          front: 'A slot carries no data — streaming works without one. So what does it buy?',
          back: 'The guarantee that WAL a *disconnected* standby still needs will not be recycled. The cost is disk; the benefit is a late standby catching up instead of being rebuilt.',
          usedIn: ['cnpg-replication-slots'],
        },
        {
          id: 'restart-lsn',
          kind: 'command',
          front: 'Which column of `pg_replication_slots` is the whole mechanism?',
          back: '`restart_lsn` — the oldest WAL position that slot still needs. The primary will not recycle past it.',
          usedIn: ['cnpg-replication-slots'],
        },
        {
          id: 'sync-is-a-policy',
          kind: 'command',
          front: 'How do you ask for synchronous commit, and what does the operator do with it?',
          back: '`spec.postgresql.synchronous` with `method` (`any` or `first`) and `number`. You declare a policy; the operator generates `synchronous_standby_names` and keeps it correct as instances come and go.',
          usedIn: ['cnpg-synchronous-replication'],
        },
        {
          id: 'primary-in-its-own-list',
          kind: 'lecture',
          front: 'Why does the generated `synchronous_standby_names` include the primary itself?',
          back: 'Any instance may be primary later, and a primary never counts itself as a standby. With `method: any` the standbys report `sync_state = quorum` — a pool, not a ranked list.',
          usedIn: ['cnpg-synchronous-replication'],
        },
        {
          id: 'syncrep-wait',
          kind: 'lecture',
          front: 'A write hangs with too few standbys. Which wait event, and why will `statement_timeout` not save you?',
          back: '`wait_event = SyncRep`. The statement has finished executing; what is outstanding is the commit acknowledgement, which no statement timer covers.',
          usedIn: ['cnpg-synchronous-replication'],
        },
        {
          id: 'data-durability',
          kind: 'lecture',
          front: '`dataDurability: required` versus `preferred` — what changes?',
          back: '`required` (the default) stops writes to keep the promise. `preferred` shrinks the generated list to the standbys that can answer, so writes continue and the guarantee quietly relaxes.',
          usedIn: ['cnpg-synchronous-replication'],
        },
        {
          id: 'replica-cluster-vs-instance',
          kind: 'lecture',
          front: 'What is a replica *cluster*, as opposed to another instance?',
          back: 'A separate Cluster object — its own name, Services, Secrets and lifecycle — that follows another. The shape used across namespaces, Kubernetes clusters and regions.',
          usedIn: ['cnpg-replica-cluster'],
        },
        {
          id: 'replica-cluster-fields',
          kind: 'command',
          front: 'Which two fields make a Cluster into a replica of another?',
          back: '`bootstrap.pg_basebackup` clones the source once; `replica.enabled` keeps it a standby afterwards instead of letting it promote itself when the clone finishes.',
          usedIn: ['cnpg-replica-cluster'],
        },
        {
          id: 'detach-timeline',
          kind: 'lecture',
          front: 'You set `replica.enabled: false`. What proves it is now its own database?',
          back: 'The timeline goes 1 → 2. A promotion starts a new lineage, so the histories diverge for good — which is why detaching is not reversible.',
          usedIn: ['cnpg-replica-cluster'],
        },
        {
          id: 'streaming-replica-role-limit',
          kind: 'lecture',
          front: 'Why can\'t `streaming_replica` be used for a logical replication subscription?',
          back: 'The source\'s generated `pg_hba` admits it by certificate only to the `postgres` database and the replication pseudo-database. Your tables are not there.',
          usedIn: ['cnpg-logical-replication'],
        },
        {
          id: 'logical-two-privileges',
          kind: 'lecture',
          front: 'Which two privileges does the subscribing role need, and how does each fail?',
          back: '`REPLICATION`, or the publisher refuses the connection outright. `SELECT` on the published tables, or the subscription applies cleanly and the initial copy fails with "permission denied for table".',
          usedIn: ['cnpg-logical-replication'],
        },
        {
          id: 'logical-no-ddl',
          kind: 'lecture',
          front: 'Logical replication does not carry DDL. What does that failure look like?',
          back: 'The Subscription reports `applied: false` with `relation "public.orders" does not exist`. Create the table on the subscriber and the operator heals it within a minute, nothing re-applied.',
          usedIn: ['cnpg-logical-replication'],
        },
        {
          id: 'publication-db-name',
          kind: 'command',
          front: 'What is `publicationDBName` for?',
          back: 'It names the database the publication actually lives in, when the external cluster connects to a different one. Omit it and the subscription applies, reports healthy, and does nothing.',
          usedIn: ['cnpg-logical-replication'],
        },
        {
          id: 'logical-slot-hazard',
          kind: 'lecture',
          front: 'What does a subscription create on the publisher, and why does an abandoned one matter?',
          back: 'A *logical* replication slot, which retains WAL exactly as a physical one does. An abandoned subscription is an operational hazard, not a tidy-up job.',
          usedIn: ['cnpg-logical-replication'],
        },
        {
          id: 'five-sensitive-params',
          kind: 'lecture',
          front: 'Which settings may a standby never hold at a lower value than its primary?',
          back: '`max_connections`, `max_worker_processes`, `max_wal_senders`, `max_prepared_transactions` and `max_locks_per_transaction`. A standby below its primary cannot start hot standby at all.',
          usedIn: ['cnpg-hot-standby-params'],
        },
        {
          id: 'control-file-channel',
          kind: 'command',
          front: "How does a standby learn the primary's value for one of those settings?",
          back: "From the WAL's parameter-change record, which it writes into its own control file — so `pg_controldata` on a standby reports the *primary's* numbers, not its own configuration.",
          usedIn: ['cnpg-hot-standby-params'],
        },
        {
          id: 'why-replicas-first',
          kind: 'lecture',
          front: 'Why does the operator roll standbys before the primary for these parameters?',
          back: 'Raising the primary first would leave the standbys below it, and they would refuse to serve reads. The order does not reverse for a decrease — one order is safe in both directions.',
          usedIn: ['cnpg-hot-standby-params'],
        },
      ],
    },

    {
      id: 'lifecycle',
      title: 'Fencing, hibernation and configuration',
      blurb: 'Stopping things without destroying them, and what a config change costs.',
      cards: [
        {
          id: 'fencing-what-stops',
          kind: 'lecture',
          front: 'What does fencing an instance stop, and what does it leave running?',
          back: 'Stops PostgreSQL only. The Pod stays with `restartCount` 0, the PVC stays bound, and only `/controller/manager` runs inside — the socket is gone.',
          usedIn: ['cnpg-fencing'],
        },
        {
          id: 'fencing-interface',
          kind: 'command',
          front: 'What is the actual interface for fencing, behind the plugin?',
          back: 'The annotation `cnpg.io/fencedInstances`, holding a JSON list of instance names. `kubectl cnpg fencing on|off` is a convenience over `kubectl annotate`.',
          usedIn: ['cnpg-fencing'],
        },
        {
          id: 'fencing-ready-false',
          kind: 'lecture',
          front: 'A fenced Pod is still `Running`. What takes it out of the Services?',
          back: 'Its `Ready` condition goes false about 30 seconds later, and endpoints only carry ready Pods.',
          usedIn: ['cnpg-fencing'],
        },
        {
          id: 'fencing-no-escape',
          kind: 'lecture',
          front: 'What rescues a cluster that was fenced by mistake?',
          back: 'Nothing automatic. There is no timeout and no failover out of a fence — the operator will not overrule a decision you made. Somebody must remove the annotation.',
          usedIn: ['cnpg-fencing'],
        },
        {
          id: 'hibernation-keeps',
          kind: 'lecture',
          front: 'Hibernating a cluster removes what, and keeps what?',
          back: 'Removes every instance Pod; keeps every PVC bound and the Cluster object itself. The Services survive with no endpoints, so connections are refused.',
          usedIn: ['cnpg-hibernation'],
        },
        {
          id: 'hibernation-vs-delete',
          kind: 'lecture',
          front: 'Why is hibernating not the same as deleting and restoring?',
          back: 'No backup and no restore are involved. Waking starts the instances on the data directories they already had — the ages give it away: new Pods on old volumes.',
          usedIn: ['cnpg-hibernation'],
        },
        {
          id: 'pending-restart',
          kind: 'command',
          front: 'Which column tells you whether a configuration change is already in effect?',
          back: '`pending_restart` in `pg_settings`. Check it *before* planning a change, not after.',
          usedIn: ['cnpg-config-changes'],
        },
        {
          id: 'config-three-outcomes',
          kind: 'lecture',
          front: 'A configuration change has three possible outcomes. What are they?',
          back: 'Applied on a reload with nothing restarted; applied by rolling every instance; or refused at admission because the parameter is the operator\'s to set.',
          usedIn: ['cnpg-config-changes'],
        },
        {
          id: 'primary-restarted-in-place',
          kind: 'lecture',
          front: 'A restart-required parameter rolls the cluster. What happens to the *primary*?',
          back: 'Under the default `primaryUpdateMethod: restart` its Pod is not recreated — the instance manager restarts PostgreSQL inside the running container, so `restartCount` stays 0 while `pg_postmaster_start_time` moves on.',
          usedIn: ['cnpg-config-changes'],
        },
        {
          id: 'fixed-parameters',
          kind: 'command',
          front: 'What happens if you set `listen_addresses` or `shared_preload_libraries`?',
          back: 'The admission webhook refuses the whole update: `Can\'t set fixed configuration parameter`. Nothing is stored, so there is nothing to undo.',
          usedIn: ['cnpg-config-changes'],
        },
        {
          id: 'contextual-refusal',
          kind: 'lecture',
          front: 'Why is `wal_log_hints: off` refused on this cluster but allowed on another?',
          back: 'The refusal reasons about the cluster you have: "must be set to `on` when `instances` > 1". On a single-instance cluster the rule — `pg_rewind` needing those hints — does not apply.',
          usedIn: ['cnpg-config-changes'],
        },
        {
          id: 'custom-conf',
          kind: 'command',
          front: 'Where does the operator actually write PostgreSQL parameters?',
          back: '`custom.conf` in the data directory, included from `postgresql.conf`. That is the file to read when the spec and the running value seem to disagree.',
          usedIn: ['cnpg-config-changes'],
        },
        {
          id: 'rolling-update-order',
          kind: 'lecture',
          front: 'You change `spec.imageName`. In what order does the operator replace instances?',
          back: 'Replicas first, one at a time, primary last — so a working database stays available for as long as possible. Every Pod is recreated: a container cannot change image in place.',
          usedIn: ['cnpg-rolling-update'],
        },
        {
          id: 'mixed-images-normal',
          kind: 'lecture',
          front: 'Mid-upgrade some Pods run 18.3 and others 18.4. Is the cluster broken?',
          back: 'No — that is a roll in progress, and the database answers throughout. The cluster reports "Waiting for the instances to become active" while it works through them.',
          usedIn: ['cnpg-rolling-update'],
        },
        {
          id: 'minor-no-migration',
          kind: 'lecture',
          front: 'Why does a PostgreSQL minor-version upgrade need no data migration?',
          back: 'The on-disk format is compatible, so an instance starts on the same data directory with a newer binary. The PVCs are never touched. A *major* upgrade is a different operation entirely.',
          usedIn: ['cnpg-rolling-update'],
        },
        {
          id: 'pvc-protection-finalizer',
          kind: 'lecture',
          front: 'You delete a PVC that a running Pod is mounting. What happens?',
          back: 'It reports success and then appears to do nothing: the claim sits in `Terminating` indefinitely, held by the `kubernetes.io/pvc-protection` finalizer. Deleting the Pod is what releases it.',
          usedIn: ['cnpg-pvc-deletion'],
        },
        {
          id: 'corrupt-needs-fencing',
          kind: 'lecture',
          front: 'Why must an instance be fenced before you damage its data directory?',
          back: 'The control file is rewritten on every checkpoint and on a clean shutdown, so damage done to a running instance is quietly undone when its Pod restarts. Fencing stops PostgreSQL first.',
          usedIn: ['cnpg-corrupted-pvc'],
        },
        {
          id: 'where-the-data-is',
          kind: 'lecture',
          front: 'Where does a `local-path` volume actually live on a k3s node?',
          back: '`/var/lib/rancher/k3s/storage/<volume>_<namespace>_<claim>` — an ordinary directory holding `PG_VERSION`, `base`, `global` and `pg_wal` exactly as initdb laid them out. A PersistentVolume is a path, not a special object.',
          usedIn: ['cnpg-corrupted-pvc'],
        },
        {
          id: 'noschedule-does-not-evict',
          kind: 'lecture',
          front: 'You taint a node `NoSchedule`. What happens to the database instance already on it?',
          back: 'Nothing — it keeps running and the database never notices. `NoSchedule` is consulted only when the scheduler places a Pod. `NoExecute` is the effect that removes what is already there.',
          usedIn: ['cnpg-taints-tolerations'],
        },
        {
          id: 'stranded-two-reasons',
          kind: 'lecture',
          front: 'An instance on a tainted node is deleted and will not reschedule anywhere. Why not?',
          back: 'Two reasons at once: the taint rules out its own node, and its `local-path` volume — pinned by `volume.kubernetes.io/selected-node` — rules out every other. Neither alone would strand it.',
          usedIn: ['cnpg-taints-tolerations'],
        },
        {
          id: 'toleration-changes-the-workload',
          kind: 'command',
          front: 'After adding a toleration and seeing the instance schedule, what should you check about the node?',
          back: 'That it is still tainted. A toleration under `spec.affinity.tolerations` changes who is willing to run there, not the node — and the operator writes it onto the Pod verbatim.',
          usedIn: ['cnpg-taints-tolerations'],
        },
      ],
    },

    {
      id: 'failover',
      title: 'Failover and switchover',
      blurb: 'Losing a primary on purpose, and how fast the endpoint follows.',
      cards: [
        {
          id: 'failover-vs-switchover',
          kind: 'lecture',
          front: 'Failover versus switchover — what is the difference?',
          back: 'A failover is the operator reacting to a primary that is gone. A switchover is a planned promotion you ask for, with the old primary demoted to a standby rather than lost.',
          usedIn: ['cnpg-failover', 'cnpg-switchover'],
        },
        {
          id: 'cnpg-promote',
          kind: 'command',
          front: 'How do you deliberately move the primary to a named instance?',
          back: '`kubectl cnpg promote pg-cluster pg-cluster-2`. The operator demotes the old primary and it rejoins as a standby.',
          usedIn: ['cnpg-switchover'],
        },
        {
          id: 'promotion-timestamps',
          kind: 'command',
          front: 'How do you measure how long a promotion really took, after the fact?',
          back: 'The gap between `.status.targetPrimaryTimestamp` (the operator decided) and `.status.currentPrimaryTimestamp` (it became primary) — both stamped server-side.',
          usedIn: ['cnpg-failover-endpoint-time', 'cnpg-switchover-endpoint-time'],
        },
        {
          id: 'endpoint-follows',
          kind: 'lecture',
          front: 'What actually redirects clients after a failover?',
          back: 'The `-rw` Service\'s endpoint changes to the new primary\'s Pod IP. Until it does, clients are still being sent to a database that cannot accept writes.',
          usedIn: ['cnpg-failover-endpoint-time'],
        },
        {
          id: 'degraded-not-failed',
          kind: 'lecture',
          front: 'A cluster loses a replica. Why is that not a failover?',
          back: 'Degraded is not failed — there is still a primary, it takes writes, and the `-rw` Service never moves. A lost replica only needs replacing; only a lost primary demands a promotion.',
          usedIn: ['cnpg-degraded-recovery'],
        },
      ],
    },

    {
      id: 'backup',
      title: 'Backup and recovery',
      blurb: 'Object storage, volume snapshots and point-in-time recovery.',
      cards: [
        {
          id: 'barman-plugin-not-in-tree',
          kind: 'lecture',
          front: 'Why do these labs use the Barman Cloud *plugin* rather than `spec.backup.barmanObjectStore`?',
          back: 'The in-tree field still exists in 1.30 but warns on every use and is removed in 1.31. The plugin is the supported path.',
          usedIn: ['cnpg-barman-backup'],
        },
        {
          id: 'pitr-target',
          kind: 'command',
          front: 'How do you recover a cluster to a specific moment rather than to the latest WAL?',
          back: 'Bootstrap with `recovery` and a `recoveryTarget` — `targetTime` for a timestamp. The new cluster replays the archive up to that point and stops.',
          usedIn: ['cnpg-pitr'],
        },
        {
          id: 'wal-maxparallel',
          kind: 'lecture',
          front: 'What does `wal.maxParallel` change during a restore?',
          back: 'How many WAL segments are fetched at once. Measured here: three sequential recoveries took 81, 72 and 91 seconds against 61, 56 and 60 with `maxParallel: 8`.',
          usedIn: ['cnpg-wal-restore'],
        },
        {
          id: 'snapshot-needs-csi',
          kind: 'lecture',
          front: 'Why can\'t volume-snapshot backups work on a default k3s cluster?',
          back: 'Its `local-path` storage class cannot snapshot. Snapshots need a CSI driver that supports them, plus the external-snapshotter CRDs.',
          usedIn: ['cnpg-volume-snapshots'],
        },
        {
          id: 'restore-is-a-new-cluster',
          kind: 'lecture',
          front: 'Does CloudNativePG restore into an existing cluster?',
          back: 'No. Recovery is a *bootstrap method* — a new Cluster whose `bootstrap` says `recovery` instead of `initdb`. The original keeps running untouched, so you end with a second database with its own Services and credentials.',
          usedIn: ['cnpg-barman-restore'],
        },
        {
          id: 'servername-routes-recovery',
          kind: 'command',
          front: "One bucket holds several clusters' backups. What makes a recovery read the right one?",
          back: '`serverName` in the `externalClusters` entry, alongside the Barman plugin and the ObjectStore to read from.',
          usedIn: ['cnpg-barman-restore', 'cnpg-replica-from-backup'],
        },
        {
          id: 'replica-enabled-turns-restore',
          kind: 'command',
          front: 'Which single field turns a restore-from-backup into a replica instead of a new primary?',
          back: '`replica.enabled`. Without it the recovered cluster promotes itself onto its own timeline; with it, it stays in recovery and keeps replaying whatever the source archives.',
          usedIn: ['cnpg-replica-from-backup'],
        },
        {
          id: 'archive-replica-no-receiver',
          kind: 'command',
          front: 'How can you tell a replica is fed by an archive rather than by streaming?',
          back: 'It has no WAL receiver: `pg_last_wal_receive_lsn` stays empty while `pg_last_wal_replay_lsn` advances — and the source\'s `pg_stat_replication` never lists it at all.',
          usedIn: ['cnpg-replica-from-backup'],
        },
        {
          id: 'archive-replica-latency',
          kind: 'lecture',
          front: 'Why does a row take longer to reach an archive-fed replica than a streaming one?',
          back: 'Its latency is a whole WAL segment: nothing arrives until the segment carrying it is archived. `SELECT pg_switch_wal()` on the primary forces that immediately.',
          usedIn: ['cnpg-replica-from-backup'],
        },
        {
          id: 'snapshot-ready-to-use',
          kind: 'command',
          front: "What says a VolumeSnapshot's copy exists, rather than just the request for it?",
          back: '`status.readyToUse`. Behind it sits a cluster-scoped `VolumeSnapshotContent` representing the actual snapshot in the storage system.',
          usedIn: ['cnpg-replica-from-snapshot'],
        },
        {
          id: 'snapshot-crash-consistent',
          kind: 'lecture',
          front: 'Nothing quiesces the database before a volume snapshot. Why is the copy usable?',
          back: 'It is crash-consistent, exactly like pulling the power — which is fine, because recovering from a crash is what PostgreSQL does on every start.',
          usedIn: ['cnpg-replica-from-snapshot', 'cnpg-volume-snapshots'],
        },
        {
          id: 'snapshot-seed-then-stream',
          kind: 'lecture',
          front: 'A snapshot is a moment, not a stream. What has to pair with it to make a replica?',
          back: '`replica.enabled` plus a streaming `externalClusters` entry: the snapshot is the seed, streaming keeps it current. Unlike an archive-fed replica, this one has a WAL receiver.',
          usedIn: ['cnpg-replica-from-snapshot'],
        },
      ],
    },

    {
      id: 'observability',
      title: 'Metrics and logs',
      blurb: 'What every instance already exports, and the shape of its logs.',
      cards: [
        {
          id: 'metrics-port',
          kind: 'command',
          front: 'Which ports serve Prometheus metrics for an instance and for a pooler?',
          back: '9187 for a database instance, 9127 for a PgBouncer Pod. A scrape config that assumes one silently misses the other.',
          usedIn: ['cnpg-metrics', 'cnpg-pgbouncer-metrics'],
        },
        {
          id: 'collector-up-first',
          kind: 'lecture',
          front: 'Which metric should you alert on before any of the others?',
          back: '`cnpg_collector_up`. A dashboard full of stale values with `collector_up 0` behind it is the classic misleading monitoring failure.',
          usedIn: ['cnpg-metrics'],
        },
        {
          id: 'custom-query-metric',
          kind: 'command',
          front: 'How do you export a metric about *your* data rather than about PostgreSQL?',
          back: 'SQL in a ConfigMap referenced by `spec.monitoring.customQueriesConfigMap`. The family name and column become `cnpg_<family>_<column>`.',
          usedIn: ['cnpg-metrics'],
        },
        {
          id: 'json-logs-default',
          kind: 'lecture',
          front: 'What log format does CloudNativePG use, and what can you switch it to?',
          back: 'Structured JSON, always — there is no plain-text mode. PostgreSQL\'s own CSV log fields arrive nested under a `record` key.',
          usedIn: ['cnpg-json-logs'],
        },
        {
          id: 'find-by-sqlstate',
          kind: 'command',
          front: 'Why search logs by `sql_state_code` rather than by the error message?',
          back: 'It is a stable five-character code, so it finds that class of failure regardless of message wording or locale. Division by zero is `22012`.',
          usedIn: ['cnpg-json-logs'],
        },
        {
          id: 'logs-cluster-aggregate',
          kind: 'command',
          front: 'How do you read every instance\'s log as one stream?',
          back: '`kubectl cnpg logs cluster pg-cluster`, tagged per Pod by `logging_pod`. `-f` follows Pods created while it runs, which is what makes it usable during a failover.',
          usedIn: ['cnpg-json-logs'],
        },
      ],
    },
  ],
}
