// CloudNativePG index cards.
//
// One deck per technology; this is the CNPG one. Each card is a single question and a short
// answer, drawn from the two places the labs' knowledge already lives: the Command Reference
// (`src/reference/cnpg.js`) and the lecture notes on each lab's detail page
// (`catalog.json`'s `lectureNotes`). See CLAUDE.md, "Index card contract".
//
// The rule that keeps these honest is the same one that governs the reference: nothing here
// is invented. Every fact on a `back` was observed in a real run against a real k3d +
// CloudNativePG cluster, or is the plain reading of a spec field the labs actually set. A
// card is a *recall prompt*, not a summary — if the answer needs a paragraph, it belongs in
// the reference or the lecture notes and the card should ask a narrower question.

export const cnpgCards = {
  id: 'cnpg',
  title: 'CloudNativePG',
  blurb: 'Recall prompts for the commands and the concepts the CloudNativePG labs teach.',
  intro: `Each card asks one question and answers it in a line or two. They come from the same material as the **Command Reference** and the labs' lecture notes, compressed to the point where you can test yourself rather than read.

Cards tagged *command* come from the Command Reference and are about what to type and what comes back; cards tagged *lecture* come from the labs' lecture notes and are about why the system behaves as it does. Both carry the labs they came from, so a card you cannot answer leads straight back to the lab that teaches it.

Nothing here is illustrative. Every behaviour a card asserts was observed in a real run against a real cluster.`,

  groups: [
    {
      id: 'survey',
      title: 'Surveying a cluster',
      blurb: 'The handful of reads every lab opens with.',
      cards: [
        {
          id: 'who-is-primary',
          kind: 'command',
          front: 'How do you ask a CloudNativePG cluster which instance is primary right now?',
          back: '`kubectl get cluster pg-cluster -o jsonpath=\'{.status.currentPrimary}\'`. Ask, never assume — it changes on every failover and switchover.',
          usedIn: ['cnpg-failover', 'cnpg-switchover'],
        },
        {
          id: 'cluster-healthy-phrase',
          kind: 'command',
          front: 'What exact phrase does a healthy Cluster report in `.status.phase`?',
          back: '`Cluster in healthy state`. Anything else — "Creating a new replica", "Waiting for the instances to become active" — means work is in progress.',
          usedIn: ['cnpg-cluster-creation'],
        },
        {
          id: 'running-image-vs-spec',
          kind: 'lecture',
          front: 'Why read a Pod\'s image from `.status.containerStatuses[0].image` rather than its spec?',
          back: 'The spec is what it was asked to run; the status is what it is running. During a rolling update they differ, which is exactly when you need to know.',
          usedIn: ['cnpg-rolling-update'],
        },
        {
          id: 'cnpg-status',
          kind: 'command',
          front: 'Which single command summarises a whole cluster — primary, instances, WAL position, replication?',
          back: '`kubectl cnpg status pg-cluster`, from the cnpg kubectl plugin.',
          usedIn: ['cnpg-switchover', 'cnpg-fencing'],
        },
        {
          id: 'one-cluster-selector',
          kind: 'command',
          front: "How do you list every object CloudNativePG generated for a cluster?",
          back: "`kubectl get all,pvc,secret -l cnpg.io/cluster=pg-cluster`. Claims and Secrets have to be named explicitly — `all` does not include them.",
          usedIn: ['cnpg-object-metadata'],
        },
        {
          id: 'rw-service-is-a-selector',
          kind: 'lecture',
          front: "How does the read-write Service know which Pod is the primary?",
          back: "It does not. It selects `cnpg.io/instanceRole=primary`, and the operator's job is to keep exactly one Pod carrying that label. A failover is a relabelling.",
          usedIn: ['cnpg-object-metadata'],
        },
        {
          id: 'relabel-reverted',
          kind: 'lecture',
          front: "You relabel a replica `cnpg.io/instanceRole=primary` by hand. How long does it last?",
          back: "About a second. The operator recomputes the role from the cluster's real state on every event, and the read-write Service never gains a second endpoint.",
          usedIn: ['cnpg-object-metadata'],
        },
        {
          id: 'node-serial-ties-pvc',
          kind: 'command',
          front: "Which annotation ties an instance Pod to its PersistentVolumeClaim?",
          back: "`cnpg.io/nodeSerial` — the number in the instance name — is written on both, which is how a rebuilt Pod finds its own volume.",
          usedIn: ['cnpg-object-metadata'],
        },
      ],
    },

    {
      id: 'operator',
      title: 'The operator',
      blurb: 'Installing it, upgrading it, and what happens when it is not there.',
      cards: [
        {
          id: 'server-side-apply',
          kind: 'command',
          front: 'Why must the CloudNativePG operator manifest be applied with `--server-side`?',
          back: 'Its CRDs are far larger than the 256 KB limit on a client-side apply\'s last-applied annotation, so a plain `kubectl apply` fails outright.',
          usedIn: ['cnpg-operator-install', 'cnpg-operator-upgrade'],
        },
        {
          id: 'operator-upgrade-instances',
          kind: 'lecture',
          front: 'What happens to running PostgreSQL instances when you upgrade the operator?',
          back: 'Nothing. Pod ages keep climbing and restart counts stay at 0 — the operator is not on the data path, which is what makes a minor upgrade routine.',
          usedIn: ['cnpg-operator-upgrade'],
        },
        {
          id: 'operator-scaled-to-zero',
          kind: 'lecture',
          front: 'The operator is scaled to zero. What breaks first?',
          back: 'Creating or changing a Cluster: the admission webhook has no endpoints, so the API server refuses the request. Existing databases keep serving.',
          usedIn: ['cnpg-operator-deployment'],
        },
        {
          id: 'operator-ha-lease',
          kind: 'lecture',
          front: 'Three operator replicas are running. How many are doing work, and what decides which?',
          back: 'One. Leader election through a Lease; the others stand by. Deleting the holder saw a standby take over in about 2 seconds, because a clean shutdown releases the Lease rather than letting it expire.',
          usedIn: ['cnpg-operator-ha'],
        },
        {
          id: 'operator-eviction-pdb',
          kind: 'lecture',
          front: 'Why can a single-replica operator with a `minAvailable: 1` PodDisruptionBudget hang a node drain?',
          back: 'The Eviction API returns `TooManyRequests` forever — the budget can never be satisfied by evicting the only replica. A second replica resolves it.',
          usedIn: ['cnpg-operator-eviction'],
        },
        {
          id: 'operator-config-absent',
          kind: 'lecture',
          front: 'What operator-wide configuration does a default installation actually have?',
          back: 'None. It starts with `--config-map-name=cnpg-controller-manager-config` and a matching secret name, and neither object exists until someone creates it.',
          usedIn: ['cnpg-operator-configmap'],
        },
        {
          id: 'operator-config-startup',
          kind: 'lecture',
          front: 'You edit the operator ConfigMap. When does the change take effect?',
          back: 'Not until the operator restarts — it is read once, at startup. Editing it and waiting achieves nothing.',
          usedIn: ['cnpg-operator-configmap'],
        },
        {
          id: 'operator-pod-deleted',
          kind: 'lecture',
          front: 'You delete the operator Pod. What happens to queries in flight?',
          back: 'Nothing — the operator is not on the data path. The Deployment replaces the Pod, the new process takes the leader-election Lease, and reconciliation resumes while the database never pauses.',
          usedIn: ['cnpg-operator-pod-deletion'],
        },
        {
          id: 'operator-zero-consequence',
          kind: 'lecture',
          front: 'With the operator scaled to zero, you delete an instance Pod. What happens?',
          back: 'Nothing replaces it. The cluster keeps serving on the instances that remain — what you lose with the operator is reconciliation, not availability.',
          usedIn: ['cnpg-operator-pod-deletion', 'cnpg-operator-deployment'],
        },
        {
          id: 'image-catalog-schema',
          kind: 'command',
          front: 'An ImageCatalog is rejected with a strict-decoding error. What is the likely mistake?',
          back: '`major` put under `spec.componentImages`. `spec.images` is the required list and takes `{major, image}`; `componentImages` is a separate list keyed by `{key, image}` for non-PostgreSQL components.',
          usedIn: ['cnpg-image-catalog'],
        },
        {
          id: 'image-catalog-swap',
          kind: 'command',
          front: 'Why must removing `spec.imageName` and adding `imageCatalogRef` be a single patch?',
          back: 'A Cluster may name an image or reference a catalog, never both — so the remove and the add go in one atomic JSON patch rather than two steps.',
          usedIn: ['cnpg-image-catalog'],
        },
        {
          id: 'image-catalog-lever',
          kind: 'lecture',
          front: 'What does referencing a catalog buy over naming the image directly?',
          back: 'The upgrade lever moves off the Cluster. Editing the catalog rolls every cluster referencing it, and those clusters cannot drift from it because they have no image of their own.',
          usedIn: ['cnpg-image-catalog'],
        },
        {
          id: 'instance-manager-pid1',
          kind: 'lecture',
          front: "What runs as PID 1 inside a CloudNativePG postgres container?",
          back: "`/controller/manager instance run` — the instance manager, a binary from the operator image. PostgreSQL is its child process.",
          usedIn: ['cnpg-in-place-upgrade'],
        },
        {
          id: 'inplace-updates-key',
          kind: 'command',
          front: "Which operator ConfigMap key lets an upgrade skip restarting the databases?",
          back: "`ENABLE_INSTANCE_MANAGER_INPLACE_UPDATES=true` — INPLACE as one word, and read only at operator startup.",
          usedIn: ['cnpg-in-place-upgrade'],
        },
        {
          id: 'confirm-operator-config',
          kind: 'command',
          front: "How do you confirm an operator ConfigMap setting was actually loaded?",
          back: "Grep the operator log for `Operator configuration loaded` — it prints the whole configuration, so an unrecognised key shows up as the default rather than as an error.",
          usedIn: ['cnpg-in-place-upgrade'],
        },
        {
          id: 'inplace-evidence',
          kind: 'lecture',
          front: "What proves an instance manager was upgraded in place rather than by replacing the Pod?",
          back: "The Pod creation timestamps do not move and restart counts stay at 0 while `cnpg.io/operatorVersion` changes — and PostgreSQL's own uptime spans the upgrade.",
          usedIn: ['cnpg-in-place-upgrade'],
        },
      ],
    },

    {
      id: 'cluster',
      title: 'Clusters and storage',
      blurb: 'Instances, volumes, and what scaling actually creates and destroys.',
      cards: [
        {
          id: 'scale-up-objects',
          kind: 'lecture',
          front: 'You change `spec.instances` from 3 to 4. What does the operator create?',
          back: 'A PersistentVolumeClaim, a short-lived `*-join-*` Pod running `pg_basebackup` against the primary, a replication slot, and the instance itself.',
          usedIn: ['cnpg-cluster-scaling'],
        },
        {
          id: 'scale-down-removes',
          kind: 'lecture',
          front: 'Scaling down removes an instance. What else goes with it, and which instance is chosen?',
          back: 'Its PVC *and* its replication slot, both deleted rather than orphaned. Always the highest-numbered instance — you do not get to choose.',
          usedIn: ['cnpg-cluster-scaling'],
        },
        {
          id: 'orphan-slot-danger',
          kind: 'lecture',
          front: 'Why is a replication slot left behind for a removed instance dangerous?',
          back: 'The primary reserves WAL for it forever. The first symptom is a full volume, which looks nothing like a replication problem.',
          usedIn: ['cnpg-cluster-scaling', 'cnpg-replication-slots'],
        },
        {
          id: 'new-replica-clone',
          kind: 'lecture',
          front: 'Why does a newly added instance already hold rows written before it existed?',
          back: 'It is cloned from the primary with `pg_basebackup`, not replayed from empty. The cost of scaling up is copying the data directory, not replaying history.',
          usedIn: ['cnpg-cluster-scaling'],
        },
        {
          id: 'pvc-per-instance',
          kind: 'lecture',
          front: 'How many PersistentVolumeClaims does a 3-instance cluster have, and what are they called?',
          back: 'One per instance Pod, named identically to it — `pg-cluster-1`, `-2`, `-3` — created automatically, with no PVC in the manifest.',
          usedIn: ['cnpg-persistent-volume'],
        },
        {
          id: 'local-path-pinning',
          kind: 'lecture',
          front: 'Why can a `local-path` volume never move to another node?',
          back: 'It provisions a hostPath directory on the node the Pod first scheduled to, recorded on the claim as `volume.kubernetes.io/selected-node`. Unlike a cloud CSI volume it cannot reattach anywhere else.',
          usedIn: ['cnpg-persistent-volume'],
        },
        {
          id: 'bootstrap-is-one-shot',
          kind: 'lecture',
          front: 'You patch `spec.bootstrap.initdb.database` on a running cluster. What happens?',
          back: 'It is accepted with no warning and has no effect. `bootstrap` is a one-shot instruction carried out at creation, never consulted again — so the spec permanently describes a database that does not exist.',
          usedIn: ['cnpg-initdb'],
        },
        {
          id: 'initdb-two-hooks',
          kind: 'command',
          front: 'What is the difference between `postInitSQL` and `postInitApplicationSQL`?',
          back: 'Which database they run in. `postInitSQL` runs in `postgres` as superuser; `postInitApplicationSQL` runs inside the application database. A `CREATE TABLE` in the wrong one lands somewhere nobody wants it.',
          usedIn: ['cnpg-initdb'],
        },
        {
          id: 'checksums-pg18-default',
          kind: 'lecture',
          front: '`data_checksums` is on in a cluster that never asked for it. Why?',
          back: "PostgreSQL 18's own initdb enables checksums by default. CloudNativePG's `dataChecksums` only controls whether `-k` is passed — on 18 the thing you would have to ask for is turning them off.",
          usedIn: ['cnpg-initdb'],
        },
        {
          id: 'initdb-permanent-choices',
          kind: 'lecture',
          front: 'Which initdb choices can never be changed without rebuilding the cluster?',
          back: 'The physical ones written into the data directory — WAL segment size, checksums, encoding and collation. Changing encoding or collation means a dump and restore into a new cluster, not a replica.',
          usedIn: ['cnpg-initdb'],
        },
        {
          id: 'inherited-metadata-field',
          kind: 'command',
          front: "Which field labels everything the operator generates from a Cluster?",
          back: "`spec.inheritedMetadata`, holding labels and annotations. They reach the Pods, claims, Services and Secret within seconds, and nothing is recreated for it.",
          usedIn: ['cnpg-inherited-metadata'],
        },
        {
          id: 'inheritance-is-additive',
          kind: 'lecture',
          front: "You remove a key from `spec.inheritedMetadata`. What happens to the objects carrying it?",
          back: "Nothing. They keep it indefinitely — inheritance is additive, and only replacing the object removes the label.",
          usedIn: ['cnpg-inherited-metadata'],
        },
        {
          id: 'merge-patch-null',
          kind: 'command',
          front: "Why does a merge patch that leaves a label out fail to remove it?",
          back: "Merge patches merge maps: an omitted key was not mentioned, not removed. Send the key with a value of `null` to take it out.",
          usedIn: ['cnpg-inherited-metadata'],
        },
        {
          id: 'inherit-instancerole',
          kind: 'lecture',
          front: "What happens if you inherit `cnpg.io/instanceRole: primary`?",
          back: "Inherited metadata is applied last, so it wins: every Pod claims to be primary, the read-write Service gains an endpoint per instance, and writes fail with `cannot execute INSERT in a read-only transaction`.",
          usedIn: ['cnpg-inherited-metadata'],
        },
        {
          id: 'expansion-is-a-class-property',
          kind: 'lecture',
          front: "What decides whether a database volume can be grown at all?",
          back: "`allowVolumeExpansion` on the StorageClass. Absent means false, and the API server refuses the request before the operator or the driver sees it.",
          usedIn: ['cnpg-storage-expansion'],
        },
        {
          id: 'requested-vs-capacity',
          kind: 'command',
          front: "Which two fields tell you whether a volume resize has finished?",
          back: "`spec.resources.requests.storage` is what was asked for and moves at once; `status.capacity.storage` is what the volume is and follows a minute or so later.",
          usedIn: ['cnpg-storage-expansion'],
        },
        {
          id: 'expansion-one-way',
          kind: 'lecture',
          front: "Can a CloudNativePG volume be made smaller again?",
          back: "No. The operator's webhook refuses it — `can't shrink existing storage from 2Gi to 1Gi` — so the size you choose is a floor, not a target.",
          usedIn: ['cnpg-storage-expansion'],
        },
        {
          id: 'expansion-not-replacement',
          kind: 'command',
          front: "How do you tell an expansion from a replacement, given the claim keeps its name?",
          back: "`spec.volumeName` — the volume behind the claim. The same volume means it grew; a new one means the instance was rebuilt.",
          usedIn: ['cnpg-storage-expansion'],
        },
        {
          id: 'walstorage-symlink',
          kind: 'lecture',
          front: "What does `spec.walStorage` do to the data directory?",
          back: "It turns `pg_wal` into a symbolic link to `/var/lib/postgresql/wal/pg_wal`, on a second claim mounted into the Pod. PostgreSQL writes to the same path as always.",
          usedIn: ['cnpg-wal-volume'],
        },
        {
          id: 'walstorage-one-way',
          kind: 'lecture',
          front: "Can a WAL volume be removed from a cluster once it has one?",
          back: "No — `walStorage cannot be disabled once configured`. The size can still be grown; the volume itself is a one-way door.",
          usedIn: ['cnpg-wal-volume'],
        },
        {
          id: 'walstorage-default-class',
          kind: 'command',
          front: "Which StorageClass do the WAL claims land on?",
          back: "The cluster's *default* class, unless `walStorage.storageClass` names one — an easy way to put the log on slower storage than the data.",
          usedIn: ['cnpg-wal-volume'],
        },
        {
          id: 'import-microservice',
          kind: 'command',
          front: "What does `type: microservice` do to the database being imported?",
          back: "Restores exactly one database into the new cluster's own `app` database and reassigns its objects to that cluster's `app` user. It imports no roles.",
          usedIn: ['cnpg-import-microservice'],
        },
        {
          id: 'import-monolith',
          kind: 'command',
          front: "What does `type: monolith` keep that a microservice import does not?",
          back: "Database names and owners, and the roles themselves — attributes such as NOLOGIN, their grants, and their password hashes.",
          usedIn: ['cnpg-import-monolith'],
        },
        {
          id: 'import-needs-superuser',
          kind: 'lecture',
          front: "Why does a logical import have to connect as a superuser?",
          back: "pg_dump must read objects the application user does not own, and a monolith import also runs `pg_dumpall --roles-only`. On a CloudNativePG source that means `enableSuperuserAccess`.",
          usedIn: ['cnpg-import-microservice', 'cnpg-import-monolith'],
        },
        {
          id: 'import-monolith-no-app-user',
          kind: 'lecture',
          front: "What is missing from a cluster created by a monolith import?",
          back: "An application database, an application user and a `-app` Secret. Every credential in it came out of the dump and is yours to manage.",
          usedIn: ['cnpg-import-monolith'],
        },
        {
          id: 'import-is-a-moment',
          kind: 'lecture',
          front: "How far behind the source does an imported cluster stay?",
          back: "It stops at the instant pg_dump read the source. Nothing follows afterwards — no slot, no receiver, no subscription — so the cutover window is however long the dump and restore take.",
          usedIn: ['cnpg-import-microservice'],
        },
        {
          id: 'tablespace-one-per-instance',
          kind: 'lecture',
          front: 'How many volumes does one declared tablespace create on a three-instance cluster?',
          back: 'Three — one claim per instance, named `<instance>-tbs-<tablespace>`. A standby replays into files of its own, so it needs its own copy of the directory.',
          usedIn: ['cnpg-tablespaces'],
        },
        {
          id: 'tablespace-rolls-cluster',
          kind: 'lecture',
          front: 'Why does declaring a tablespace roll the cluster?',
          back: 'Attaching a volume means replacing the Pods. The phase moves through "Waiting for the instances to become active" while `status.tablespacesStatus` goes pending → reconciled.',
          usedIn: ['cnpg-tablespaces'],
        },
        {
          id: 'tablespace-symlink',
          kind: 'command',
          front: 'Where can you see how a tablespace is actually implemented?',
          back: '`ls -l /var/lib/postgresql/data/pgdata/pg_tblspc/` — one symlink per tablespace, named after its OID, pointing at `/var/lib/postgresql/tablespaces/<name>/data`.',
          usedIn: ['cnpg-tablespaces'],
        },
        {
          id: 'tablespace-no-delete',
          kind: 'command',
          front: 'What happens if you remove a tablespace from spec.tablespaces?',
          back: 'Refused at admission: `no tablespace can be deleted once created`. Adding one is a decision about every instance for as long as the cluster exists.',
          usedIn: ['cnpg-tablespaces'],
        },
        {
          id: 'tablespace-defaults',
          kind: 'command',
          front: 'What does the webhook add to a tablespace entry you wrote by hand?',
          back: '`owner` (the application user), `temporary: false` and `storage.resizeInUseVolumes: true`. A merge patch replaces the whole list, so later changes must resend everything.',
          usedIn: ['cnpg-tablespaces'],
        },
        {
          id: 'temp-tablespace-field',
          kind: 'command',
          front: 'How do you send spilled sorts to a volume of their own?',
          back: '`temporary: true` on a `spec.tablespaces` entry. The operator creates the tablespace and writes its name into PostgreSQL\'s `temp_tablespaces` on every instance.',
          usedIn: ['cnpg-temporary-tablespaces'],
        },
        {
          id: 'temp-tablespace-evidence',
          kind: 'lecture',
          front: 'With a temporary tablespace set, what should base/pgsql_tmp in the data directory look like?',
          back: 'Present but empty — PostgreSQL creates it at startup either way. Emptiness is the evidence, not absence; the files pile up in a `pgsql_tmp` inside the tablespace.',
          usedIn: ['cnpg-temporary-tablespaces'],
        },
        {
          id: 'temp-files-counters',
          kind: 'command',
          front: 'Which counters tell you a workload is spilling to disk?',
          back: '`temp_files` and `temp_bytes` in `pg_stat_database` — cumulative per instance, reset only by a restart. A 64kB-work_mem sort took them from 1 / 2734 kB to 3 / 107 MB.',
          usedIn: ['cnpg-temporary-tablespaces'],
        },
        {
          id: 'standby-spills',
          kind: 'lecture',
          front: 'Do read-only queries on a standby use a temporary tablespace?',
          back: 'Yes, their own copy of it. One standby reported 2 files / 22 MB and the other nothing — stats are per-instance and not replicated, so monitoring must scrape every instance.',
          usedIn: ['cnpg-temporary-tablespaces'],
        },
      ],
    },

    {
      id: 'services',
      title: 'Services and connections',
      blurb: 'The three Services, and which one a client should be using.',
      cards: [
        {
          id: 'three-services',
          kind: 'lecture',
          front: 'A cluster gets `-rw`, `-ro` and `-r` Services. What is behind each?',
          back: '`-rw` the primary only; `-ro` the replicas only; `-r` every instance. Writes must use `-rw`, since only the primary accepts them.',
          usedIn: ['cnpg-service-connectivity'],
        },
        {
          id: 'app-secret',
          kind: 'command',
          front: 'Where do an application\'s credentials come from, and what type is that Secret?',
          back: 'The operator generates `<cluster>-app` of type `kubernetes.io/basic-auth`. It also carries the host, port, database name and ready-made connection URIs.',
          usedIn: ['cnpg-service-connectivity'],
        },
        {
          id: 'pgpassword-in-pod',
          kind: 'command',
          front: 'Why does `PGPASSWORD=$X kubectl exec pod -- psql …` fail to authenticate?',
          back: 'The variable is set on the kubectl client and never reaches the container. It has to be set *inside*: `kubectl exec pod -- env PGPASSWORD=$X psql …`.',
          usedIn: ['cnpg-service-connectivity'],
        },
      ],
    },

    {
      id: 'tls',
      title: 'TLS and certificates',
      blurb: 'What the cluster issues itself, and how to replace it with your own.',
      cards: [
        {
          id: 'cluster-is-a-ca',
          kind: 'lecture',
          front: 'What does a CloudNativePG cluster generate for itself on day one?',
          back: 'A CA, a server certificate and a client certificate for replication. `<cluster>-ca` holds `ca.crt` **and** `ca.key` — it is a working CA, not just a trust anchor.',
          usedIn: ['cnpg-client-certificates', 'cnpg-server-certificates'],
        },
        {
          id: 'connection-certificate',
          kind: 'command',
          front: 'How do you issue a client certificate for a PostgreSQL role, signed by the cluster\'s own CA?',
          back: '`kubectl cnpg certificate app-client-cert --cnpg-cluster pg-cluster --cnpg-user app`. The certificate\'s common name *is* the role name — that is the identity PostgreSQL reads.',
          usedIn: ['cnpg-client-certificates'],
        },
        {
          id: 'san-must-cover-services',
          kind: 'lecture',
          front: 'Your own server certificate names only `pg-cluster-rw`. What breaks, and when?',
          back: 'Every client connecting through another Service name, at connection time, under `verify-full` — which checks the host name dialled against the certificate.',
          usedIn: ['cnpg-server-certificates'],
        },
        {
          id: 'both-secrets-together',
          kind: 'lecture',
          front: 'Why must `serverCASecret` and `serverTLSSecret` be handed to the operator together?',
          back: 'Replicas verify the primary\'s certificate against the server CA. A new certificate without its CA stops replication, not just clients.',
          usedIn: ['cnpg-server-certificates'],
        },
        {
          id: 'starttls-postgres',
          kind: 'command',
          front: 'How do you see the certificate PostgreSQL actually presents on the wire?',
          back: '`openssl s_client -starttls postgres -connect pg-cluster-rw:5432`. `-starttls postgres` is required — TLS is negotiated through PostgreSQL\'s own handshake, not from the first byte.',
          usedIn: ['cnpg-server-certificates', 'cnpg-client-certificates'],
        },
        {
          id: 'sslmode-levels',
          kind: 'lecture',
          front: '`require`, `verify-ca`, `verify-full` — what does each actually check?',
          back: '`require` encrypts and verifies nothing; `verify-ca` checks the signature chain; `verify-full` also checks the host name dialled. Only the last detects an impostor.',
          usedIn: ['cnpg-client-certificates', 'cnpg-server-certificates'],
        },
      ],
    },

    {
      id: 'pooling',
      title: 'Connection pooling',
      blurb: 'PgBouncer as a declared resource.',
      cards: [
        {
          id: 'pooler-is-declared',
          kind: 'lecture',
          front: 'What does applying a `Pooler` resource produce?',
          back: 'A PgBouncer Deployment the operator builds and manages, with its own Service — plus Prometheus metrics on port 9127, without anyone asking.',
          usedIn: ['cnpg-pgbouncer', 'cnpg-pgbouncer-metrics'],
        },
        {
          id: 'pool-appears-with-traffic',
          kind: 'lecture',
          front: 'Why does a `cnpg_pgbouncer_pools_` series for your database not exist yet?',
          back: 'PgBouncer reports pools it has actually served, not pools it is configured to allow. An alert on a never-used pool never fires, because the series is absent.',
          usedIn: ['cnpg-pgbouncer-metrics'],
        },
      ],
    },

    {
      id: 'replication',
      title: 'Replication',
      blurb: 'Slots, synchronous commit, replica clusters and logical replication.',
      cards: [
        {
          id: 'ha-slots-default',
          kind: 'lecture',
          front: 'How many replication slots does a healthy 3-instance cluster hold, and who created them?',
          back: 'Two — one physical slot per replica, named `_cnpg_<instance>`. The operator, by default: high-availability slots are on with no configuration.',
          usedIn: ['cnpg-replication-slots'],
        },
        {
          id: 'what-a-slot-buys',
          kind: 'lecture',
          front: 'A slot carries no data — streaming works without one. So what does it buy?',
          back: 'The guarantee that WAL a *disconnected* standby still needs will not be recycled. The cost is disk; the benefit is a late standby catching up instead of being rebuilt.',
          usedIn: ['cnpg-replication-slots'],
        },
        {
          id: 'restart-lsn',
          kind: 'command',
          front: 'Which column of `pg_replication_slots` is the whole mechanism?',
          back: '`restart_lsn` — the oldest WAL position that slot still needs. The primary will not recycle past it.',
          usedIn: ['cnpg-replication-slots'],
        },
        {
          id: 'sync-is-a-policy',
          kind: 'command',
          front: 'How do you ask for synchronous commit, and what does the operator do with it?',
          back: '`spec.postgresql.synchronous` with `method` (`any` or `first`) and `number`. You declare a policy; the operator generates `synchronous_standby_names` and keeps it correct as instances come and go.',
          usedIn: ['cnpg-synchronous-replication'],
        },
        {
          id: 'primary-in-its-own-list',
          kind: 'lecture',
          front: 'Why does the generated `synchronous_standby_names` include the primary itself?',
          back: 'Any instance may be primary later, and a primary never counts itself as a standby. With `method: any` the standbys report `sync_state = quorum` — a pool, not a ranked list.',
          usedIn: ['cnpg-synchronous-replication'],
        },
        {
          id: 'syncrep-wait',
          kind: 'lecture',
          front: 'A write hangs with too few standbys. Which wait event, and why will `statement_timeout` not save you?',
          back: '`wait_event = SyncRep`. The statement has finished executing; what is outstanding is the commit acknowledgement, which no statement timer covers.',
          usedIn: ['cnpg-synchronous-replication'],
        },
        {
          id: 'data-durability',
          kind: 'lecture',
          front: '`dataDurability: required` versus `preferred` — what changes?',
          back: '`required` (the default) stops writes to keep the promise. `preferred` shrinks the generated list to the standbys that can answer, so writes continue and the guarantee quietly relaxes.',
          usedIn: ['cnpg-synchronous-replication'],
        },
        {
          id: 'replica-cluster-vs-instance',
          kind: 'lecture',
          front: 'What is a replica *cluster*, as opposed to another instance?',
          back: 'A separate Cluster object — its own name, Services, Secrets and lifecycle — that follows another. The shape used across namespaces, Kubernetes clusters and regions.',
          usedIn: ['cnpg-replica-cluster'],
        },
        {
          id: 'replica-cluster-fields',
          kind: 'command',
          front: 'Which two fields make a Cluster into a replica of another?',
          back: '`bootstrap.pg_basebackup` clones the source once; `replica.enabled` keeps it a standby afterwards instead of letting it promote itself when the clone finishes.',
          usedIn: ['cnpg-replica-cluster'],
        },
        {
          id: 'detach-timeline',
          kind: 'lecture',
          front: 'You set `replica.enabled: false`. What proves it is now its own database?',
          back: 'The timeline goes 1 → 2. A promotion starts a new lineage, so the histories diverge for good — which is why detaching is not reversible.',
          usedIn: ['cnpg-replica-cluster'],
        },
        {
          id: 'streaming-replica-role-limit',
          kind: 'lecture',
          front: 'Why can\'t `streaming_replica` be used for a logical replication subscription?',
          back: 'The source\'s generated `pg_hba` admits it by certificate only to the `postgres` database and the replication pseudo-database. Your tables are not there.',
          usedIn: ['cnpg-logical-replication'],
        },
        {
          id: 'logical-two-privileges',
          kind: 'lecture',
          front: 'Which two privileges does the subscribing role need, and how does each fail?',
          back: '`REPLICATION`, or the publisher refuses the connection outright. `SELECT` on the published tables, or the subscription applies cleanly and the initial copy fails with "permission denied for table".',
          usedIn: ['cnpg-logical-replication'],
        },
        {
          id: 'logical-no-ddl',
          kind: 'lecture',
          front: 'Logical replication does not carry DDL. What does that failure look like?',
          back: 'The Subscription reports `applied: false` with `relation "public.orders" does not exist`. Create the table on the subscriber and the operator heals it within a minute, nothing re-applied.',
          usedIn: ['cnpg-logical-replication'],
        },
        {
          id: 'publication-db-name',
          kind: 'command',
          front: 'What is `publicationDBName` for?',
          back: 'It names the database the publication actually lives in, when the external cluster connects to a different one. Omit it and the subscription applies, reports healthy, and does nothing.',
          usedIn: ['cnpg-logical-replication'],
        },
        {
          id: 'logical-slot-hazard',
          kind: 'lecture',
          front: 'What does a subscription create on the publisher, and why does an abandoned one matter?',
          back: 'A *logical* replication slot, which retains WAL exactly as a physical one does. An abandoned subscription is an operational hazard, not a tidy-up job.',
          usedIn: ['cnpg-logical-replication'],
        },
        {
          id: 'five-sensitive-params',
          kind: 'lecture',
          front: 'Which settings may a standby never hold at a lower value than its primary?',
          back: '`max_connections`, `max_worker_processes`, `max_wal_senders`, `max_prepared_transactions` and `max_locks_per_transaction`. A standby below its primary cannot start hot standby at all.',
          usedIn: ['cnpg-hot-standby-params'],
        },
        {
          id: 'control-file-channel',
          kind: 'command',
          front: "How does a standby learn the primary's value for one of those settings?",
          back: "From the WAL's parameter-change record, which it writes into its own control file — so `pg_controldata` on a standby reports the *primary's* numbers, not its own configuration.",
          usedIn: ['cnpg-hot-standby-params'],
        },
        {
          id: 'why-replicas-first',
          kind: 'lecture',
          front: 'Why does the operator roll standbys before the primary for these parameters?',
          back: 'Raising the primary first would leave the standbys below it, and they would refuse to serve reads. The order does not reverse for a decrease — one order is safe in both directions.',
          usedIn: ['cnpg-hot-standby-params'],
        },
      ],
    },

    {
      id: 'fencing',
      title: 'Fencing and hibernation',
      blurb: 'Stopping one instance, or a whole cluster, without destroying anything.',
      cards: [
        {
          id: 'fencing-what-stops',
          kind: 'lecture',
          front: 'What does fencing an instance stop, and what does it leave running?',
          back: 'Stops PostgreSQL only. The Pod stays with `restartCount` 0, the PVC stays bound, and only `/controller/manager` runs inside — the socket is gone.',
          usedIn: ['cnpg-fencing'],
        },
        {
          id: 'fencing-interface',
          kind: 'command',
          front: 'What is the actual interface for fencing, behind the plugin?',
          back: 'The annotation `cnpg.io/fencedInstances`, holding a JSON list of instance names. `kubectl cnpg fencing on|off` is a convenience over `kubectl annotate`.',
          usedIn: ['cnpg-fencing'],
        },
        {
          id: 'fencing-ready-false',
          kind: 'lecture',
          front: 'A fenced Pod is still `Running`. What takes it out of the Services?',
          back: 'Its `Ready` condition goes false about 30 seconds later, and endpoints only carry ready Pods.',
          usedIn: ['cnpg-fencing'],
        },
        {
          id: 'fencing-no-escape',
          kind: 'lecture',
          front: 'What rescues a cluster that was fenced by mistake?',
          back: 'Nothing automatic. There is no timeout and no failover out of a fence — the operator will not overrule a decision you made. Somebody must remove the annotation.',
          usedIn: ['cnpg-fencing'],
        },
        {
          id: 'hibernation-keeps',
          kind: 'lecture',
          front: 'Hibernating a cluster removes what, and keeps what?',
          back: 'Removes every instance Pod; keeps every PVC bound and the Cluster object itself. The Services survive with no endpoints, so connections are refused.',
          usedIn: ['cnpg-hibernation'],
        },
        {
          id: 'hibernation-vs-delete',
          kind: 'lecture',
          front: 'Why is hibernating not the same as deleting and restoring?',
          back: 'No backup and no restore are involved. Waking starts the instances on the data directories they already had — the ages give it away: new Pods on old volumes.',
          usedIn: ['cnpg-hibernation'],
        },
        {
          id: 'hibernation-annotation',
          kind: 'command',
          front: "How do you hibernate a CloudNativePG cluster declaratively?",
          back: "Annotate it `cnpg.io/hibernation=on`. Every instance Pod is removed and every claim is kept — the annotation is the whole interface, so a manifest can carry it.",
          usedIn: ['cnpg-declarative-hibernation'],
        },
        {
          id: 'hibernation-status-lies',
          kind: 'lecture',
          front: "What does `kubectl get cluster` report for a hibernated cluster?",
          back: "`Cluster in healthy state`, with a blank READY column. The honest signal is the `cnpg.io/hibernation` condition, which is removed rather than set to False on waking.",
          usedIn: ['cnpg-declarative-hibernation'],
        },
        {
          id: 'hibernated-services',
          kind: 'lecture',
          front: "What does a client see while a cluster is hibernated?",
          back: "Connection refused, not a DNS failure — the Services and Secrets survive with no endpoints behind them.",
          usedIn: ['cnpg-declarative-hibernation'],
        },
        {
          id: 'hibernation-age-mismatch',
          kind: 'command',
          front: "What proves a woken cluster reused its data rather than rebuilding it?",
          back: "Every Pod is younger than the claim it is mounted on. New processes on old disks.",
          usedIn: ['cnpg-declarative-hibernation'],
        },
      ],
    },

    {
      id: 'config',
      title: 'Configuration and upgrades',
      blurb: 'What a settings change costs, and what changing the image moves.',
      cards: [
        {
          id: 'pending-restart',
          kind: 'command',
          front: 'Which column tells you whether a configuration change is already in effect?',
          back: '`pending_restart` in `pg_settings`. Check it *before* planning a change, not after.',
          usedIn: ['cnpg-config-changes'],
        },
        {
          id: 'config-three-outcomes',
          kind: 'lecture',
          front: 'A configuration change has three possible outcomes. What are they?',
          back: 'Applied on a reload with nothing restarted; applied by rolling every instance; or refused at admission because the parameter is the operator\'s to set.',
          usedIn: ['cnpg-config-changes'],
        },
        {
          id: 'primary-restarted-in-place',
          kind: 'lecture',
          front: 'A restart-required parameter rolls the cluster. What happens to the *primary*?',
          back: 'Under the default `primaryUpdateMethod: restart` its Pod is not recreated — the instance manager restarts PostgreSQL inside the running container, so `restartCount` stays 0 while `pg_postmaster_start_time` moves on.',
          usedIn: ['cnpg-config-changes'],
        },
        {
          id: 'fixed-parameters',
          kind: 'command',
          front: 'What happens if you set `listen_addresses` or `shared_preload_libraries`?',
          back: 'The admission webhook refuses the whole update: `Can\'t set fixed configuration parameter`. Nothing is stored, so there is nothing to undo.',
          usedIn: ['cnpg-config-changes'],
        },
        {
          id: 'contextual-refusal',
          kind: 'lecture',
          front: 'Why is `wal_log_hints: off` refused on this cluster but allowed on another?',
          back: 'The refusal reasons about the cluster you have: "must be set to `on` when `instances` > 1". On a single-instance cluster the rule — `pg_rewind` needing those hints — does not apply.',
          usedIn: ['cnpg-config-changes'],
        },
        {
          id: 'custom-conf',
          kind: 'command',
          front: 'Where does the operator actually write PostgreSQL parameters?',
          back: '`custom.conf` in the data directory, included from `postgresql.conf`. That is the file to read when the spec and the running value seem to disagree.',
          usedIn: ['cnpg-config-changes'],
        },
        {
          id: 'rolling-update-order',
          kind: 'lecture',
          front: 'You change `spec.imageName`. In what order does the operator replace instances?',
          back: 'Replicas first, one at a time, primary last — so a working database stays available for as long as possible. Every Pod is recreated: a container cannot change image in place.',
          usedIn: ['cnpg-rolling-update'],
        },
        {
          id: 'mixed-images-normal',
          kind: 'lecture',
          front: 'Mid-upgrade some Pods run 18.3 and others 18.4. Is the cluster broken?',
          back: 'No — that is a roll in progress, and the database answers throughout. The cluster reports "Waiting for the instances to become active" while it works through them.',
          usedIn: ['cnpg-rolling-update'],
        },
        {
          id: 'minor-no-migration',
          kind: 'lecture',
          front: 'Why does a PostgreSQL minor-version upgrade need no data migration?',
          back: 'The on-disk format is compatible, so an instance starts on the same data directory with a newer binary. The PVCs are never touched. A *major* upgrade is a different operation entirely.',
          usedIn: ['cnpg-rolling-update'],
        },
        {
          id: 'major-upgrade-trigger',
          kind: 'command',
          front: 'How do you ask CloudNativePG for a major version upgrade?',
          back: 'Change `spec.imageName` to a new major. The operator compares it with `status.pgDataImageInfo.majorVersion` — the image that last ran on the data directory — and runs pg_upgrade instead of a rolling restart.',
          usedIn: ['cnpg-major-upgrade'],
        },
        {
          id: 'major-upgrade-job',
          kind: 'lecture',
          front: 'pg_upgrade needs both PostgreSQL installations. Where does the old one come from?',
          back: 'The `<primary>-major-upgrade` Job has an init container called `prepare` running the *old* image, which copies its installation to /controller/old — pg_upgrade’s --old-bindir.',
          usedIn: ['cnpg-major-upgrade'],
        },
        {
          id: 'major-upgrade-replicas',
          kind: 'lecture',
          front: 'What happens to the replicas during a major upgrade?',
          back: 'They are deleted and cloned again from the upgraded primary by ordinary join Jobs. The primary keeps its volume; the replica claims are minutes old afterwards.',
          usedIn: ['cnpg-major-upgrade'],
        },
        {
          id: 'major-upgrade-no-downgrade',
          kind: 'command',
          front: 'Can you go back to the previous major by editing the image again?',
          back: 'No — admission refuses it: `can\'t downgrade from major 18 to 17`. No copy of the old cluster is kept either, so the only route back is a backup taken beforehand.',
          usedIn: ['cnpg-major-upgrade'],
        },
        {
          id: 'major-upgrade-analyze',
          kind: 'lecture',
          front: 'What does reltuples = -1 mean on a table after a major upgrade?',
          back: 'Never analysed. pg_upgrade does not carry optimizer statistics, so ANALYZE — vacuumdb --analyze-in-stages in practice — is the last step of the upgrade, not a tidy-up.',
          usedIn: ['cnpg-major-upgrade'],
        },
        {
          id: 'major-upgrade-initdb-defaults',
          kind: 'lecture',
          front: 'Why does an upgraded cluster report data_checksums off while a fresh one on the same image reports on?',
          back: 'Because no initdb ever ran on the upgraded cluster — it keeps the decisions the old major’s initdb made. "On 18 now" does not mean "what 18 would have given us".',
          usedIn: ['cnpg-major-upgrade'],
        },
      ],
    },

    {
      id: 'scheduling',
      title: 'Scheduling and node operations',
      blurb: 'Where instances are allowed to run, and what happens when a node goes away.',
      cards: [
        {
          id: 'noschedule-does-not-evict',
          kind: 'lecture',
          front: 'You taint a node `NoSchedule`. What happens to the database instance already on it?',
          back: 'Nothing — it keeps running and the database never notices. `NoSchedule` is consulted only when the scheduler places a Pod. `NoExecute` is the effect that removes what is already there.',
          usedIn: ['cnpg-taints-tolerations'],
        },
        {
          id: 'stranded-two-reasons',
          kind: 'lecture',
          front: 'An instance on a tainted node is deleted and will not reschedule anywhere. Why not?',
          back: 'Two reasons at once: the taint rules out its own node, and its `local-path` volume — pinned by `volume.kubernetes.io/selected-node` — rules out every other. Neither alone would strand it.',
          usedIn: ['cnpg-taints-tolerations'],
        },
        {
          id: 'toleration-changes-the-workload',
          kind: 'command',
          front: 'After adding a toleration and seeing the instance schedule, what should you check about the node?',
          back: 'That it is still tainted. A toleration under `spec.affinity.tolerations` changes who is willing to run there, not the node — and the operator writes it onto the Pod verbatim.',
          usedIn: ['cnpg-taints-tolerations'],
        },
        {
          id: 'default-anti-affinity',
          kind: 'lecture',
          front: "A Cluster manifest mentions no scheduling. Why is there still one instance per node?",
          back: "The admission webhook defaults `podAntiAffinityType` to `preferred`, which the operator expands into a weighted anti-affinity term on `kubernetes.io/hostname`.",
          usedIn: ['cnpg-node-selector'],
        },
        {
          id: 'topology-key-lives-on-the-pod',
          kind: 'command',
          front: "Where do you read the topology key a cluster is spreading across?",
          back: "Off a Pod: `.spec.affinity.podAntiAffinity...topologyKey`. The Cluster spec does not carry it until you set one yourself.",
          usedIn: ['cnpg-node-selector'],
        },
        {
          id: 'required-single-domain',
          kind: 'lecture',
          front: "Why does `podAntiAffinityType: required` strand instances in a single-zone cluster?",
          back: "One topology domain admits one instance, so every instance after the first is unschedulable — the scheduler answers `didn't match pod anti-affinity rules`.",
          usedIn: ['cnpg-node-selector'],
        },
        {
          id: 'nodeselector-rolls',
          kind: 'lecture',
          front: "Why does adding `spec.affinity.nodeSelector` roll the whole cluster?",
          back: "The operator stamps the selector onto every instance Pod, so the running Pods no longer match the Pods it would generate — which is drift, and drift rolls.",
          usedIn: ['cnpg-node-selector'],
        },
        {
          id: 'podspec-annotation',
          kind: 'command',
          front: "Which annotation does drift detection compare against?",
          back: "`cnpg.io/podSpec`, the full Pod spec the operator recorded when it created that Pod. The comparison is against the record, not against the live object.",
          usedIn: ['cnpg-podspec-drift'],
        },
        {
          id: 'restarted-without-switchover',
          kind: 'lecture',
          front: "What does the phase `Primary instance is being restarted without a switchover` mean?",
          back: "The primary's Pod is being replaced by a rolling update and the role is not moving — the same instance is primary before and after.",
          usedIn: ['cnpg-podspec-drift'],
        },
        {
          id: 'tampered-podspec',
          kind: 'lecture',
          front: "You overwrite one Pod's `cnpg.io/podSpec` annotation with junk. What does the operator do?",
          back: "Deletes and rebuilds that Pod within a few seconds, then writes the real generated spec back. A label of your own on the same Pod is left alone.",
          usedIn: ['cnpg-podspec-drift'],
        },
        {
          id: 'endless-rollout',
          kind: 'lecture',
          front: "Why can a mutating admission webhook cause an endless rolling update of a cluster?",
          back: "It edits every Pod the operator creates, so the recorded spec never matches what the operator would generate. Exclude those Pods rather than loosening the operator.",
          usedIn: ['cnpg-podspec-drift'],
        },
        {
          id: 'tag-is-an-index',
          kind: 'lecture',
          front: "What does an image tag usually resolve to on a modern registry?",
          back: "An index listing one image per platform. The container runtime fetches it and pulls the entry matching the node it is running on.",
          usedIn: ['cnpg-multi-arch'],
        },
        {
          id: 'unknown-platform-manifests',
          kind: 'lecture',
          front: "An image index lists entries with platform `unknown/unknown`. What are they?",
          back: "Build attestations — signed provenance and a software bill of materials — not runnable images. A runtime skips them by matching on platform.",
          usedIn: ['cnpg-multi-arch'],
        },
        {
          id: 'config-blob-architecture',
          kind: 'command',
          front: "Where does an image itself state the architecture it was built for?",
          back: "In its config blob: follow the platform manifest's `.config.digest` to `/v2/<repo>/blobs/<digest>` and read `architecture` and `os`.",
          usedIn: ['cnpg-multi-arch'],
        },
        {
          id: 'digest-pinning-arch',
          kind: 'lecture',
          front: "What is the catch in pinning a container image by digest?",
          back: "An index digest keeps the multi-architecture property; a single image's digest ties the manifest to one architecture and will not schedule anywhere else.",
          usedIn: ['cnpg-multi-arch'],
        },
        {
          id: 'two-pdbs',
          kind: 'lecture',
          front: "How many PodDisruptionBudgets does CloudNativePG maintain per cluster, and why?",
          back: "Two: one over the replicas allowing a single disruption, one over the primary allowing none. A drain can take a replica at a time and never the writable instance.",
          usedIn: ['cnpg-node-drain'],
        },
        {
          id: 'drain-strands-local-storage',
          kind: 'lecture',
          front: "Why does draining a node leave a CloudNativePG instance Pending rather than moving it?",
          back: "Its local-path volume is a directory on that node, so the only node it may be scheduled to is the one you just cordoned: `1 node(s) were unschedulable, 2 node(s) didn't match PersistentVolume's node affinity`.",
          usedIn: ['cnpg-node-drain'],
        },
        {
          id: 'bare-pod-eviction',
          kind: 'lecture',
          front: "What happens to a Pod with no controller when its node is drained?",
          back: "It is deleted and never comes back — the drain warns about it in one line: `deleting Pods that declare no controller`.",
          usedIn: ['cnpg-node-drain'],
        },
        {
          id: 'maintenance-window-reusepvc',
          kind: 'command',
          front: "What does `nodeMaintenanceWindow` with `reusePVC: false` tell the operator to do?",
          back: "Stop waiting for the drained node: delete the stranded claim and rebuild the instance elsewhere with pg_basebackup. The API server also warns that `.spec.enablePDB` supersedes this field.",
          usedIn: ['cnpg-node-drain'],
        },
        {
          id: 'single-instance-drain-hangs',
          kind: 'lecture',
          front: "Why does draining a single-instance cluster's node never finish?",
          back: "Its one budget allows zero disruptions, so the eviction is refused every five seconds — `Cannot evict pod as it would violate the pod's disruption budget` — until the drain times out. The node stays cordoned regardless.",
          usedIn: ['cnpg-single-instance-drain'],
        },
        {
          id: 'enablepdb-false-cost',
          kind: 'lecture',
          front: "What does `spec.enablePDB: false` actually buy you?",
          back: "A drain that completes, and an outage: the instance is evicted with nowhere to go, and the read-write Service has no endpoints until the node is uncordoned. It makes the drain quiet, not safe.",
          usedIn: ['cnpg-single-instance-drain'],
        },
      ],
    },

    {
      id: 'integrity',
      title: 'Data integrity and cloning',
      blurb: 'Losing a volume, corrupting a page, and taking an independent copy of a running database.',
      cards: [
        {
          id: 'pvc-protection-finalizer',
          kind: 'lecture',
          front: 'You delete a PVC that a running Pod is mounting. What happens?',
          back: 'It reports success and then appears to do nothing: the claim sits in `Terminating` indefinitely, held by the `kubernetes.io/pvc-protection` finalizer. Deleting the Pod is what releases it.',
          usedIn: ['cnpg-pvc-deletion'],
        },
        {
          id: 'corrupt-needs-fencing',
          kind: 'lecture',
          front: 'Why must an instance be fenced before you damage its data directory?',
          back: 'The control file is rewritten on every checkpoint and on a clean shutdown, so damage done to a running instance is quietly undone when its Pod restarts. Fencing stops PostgreSQL first.',
          usedIn: ['cnpg-corrupted-pvc'],
        },
        {
          id: 'where-the-data-is',
          kind: 'lecture',
          front: 'Where does a `local-path` volume actually live on a k3s node?',
          back: '`/var/lib/rancher/k3s/storage/<volume>_<namespace>_<claim>` — an ordinary directory holding `PG_VERSION`, `base`, `global` and `pg_wal` exactly as initdb laid them out. A PersistentVolume is a path, not a special object.',
          usedIn: ['cnpg-corrupted-pvc'],
        },
        {
          id: 'checksum-refuses-page',
          kind: 'lecture',
          front: "What does PostgreSQL do when it reads a page whose checksum does not match?",
          back: "Refuses it — `ERROR: invalid page in block N of relation \"base/…\"` — rather than handing back plausible-looking data built out of the wrong bytes.",
          usedIn: ['cnpg-data-corruption'],
        },
        {
          id: 'checksum-failures-counts-reads',
          kind: 'lecture',
          front: "Does `pg_stat_database.checksum_failures` tell you whether your data is intact?",
          back: "No. It counts failed *reads*, so it stays at zero until something touches a damaged block — and starts again from zero after a restart.",
          usedIn: ['cnpg-data-corruption'],
        },
        {
          id: 'pg-checksums-check',
          kind: 'command',
          front: "Which tool goes looking for corruption, and what does it need?",
          back: "`pg_checksums --check -D <pgdata>`, which scans every block and reports each mismatch with both checksums. It refuses to run against a live server, so the instance has to be stopped first.",
          usedIn: ['cnpg-data-corruption'],
        },
        {
          id: 'pages-are-not-replicated',
          kind: 'lecture',
          front: "One instance has a corrupt page. Why are the other two fine?",
          back: "Physical replication ships WAL records, not pages: every standby applies the change to its own copy. Damage on one disk does not travel.",
          usedIn: ['cnpg-data-corruption'],
        },
        {
          id: 'corruption-recovery-order',
          kind: 'lecture',
          front: "A page on the primary is corrupt. What is the recovery, in order?",
          back: "Move the writes off it first with a switchover, then discard its storage and let the operator rebuild the instance from a good copy. There is no repairing a page.",
          usedIn: ['cnpg-data-corruption'],
        },
        {
          id: 'clone-vs-standby',
          kind: 'command',
          front: "Which field turns a `pg_basebackup` bootstrap into a standby rather than an independent copy?",
          back: "The `replica` stanza. Without it the copy starts up as its own primary the moment the base backup finishes.",
          usedIn: ['cnpg-basebackup-clone'],
        },
        {
          id: 'clone-brings-everything',
          kind: 'lecture',
          front: "What does a clone taken with `pg_basebackup` bring across?",
          back: "Everything — it is a physical copy of the whole data directory: every database, every role and every setting, not one application's tables.",
          usedIn: ['cnpg-basebackup-clone'],
        },
        {
          id: 'clone-is-not-a-backup',
          kind: 'lecture',
          front: "Why is a clone useless as a backup?",
          back: "It diverges immediately. Both sequences continue from the same value, so the same id soon means two different rows on two clusters, and nothing will ever reconcile them.",
          usedIn: ['cnpg-basebackup-clone'],
        },
        {
          id: 'clone-same-timeline',
          kind: 'lecture',
          front: "Why must two clusters made this way never share a WAL archive?",
          back: "A clone is never promoted, so it stays on the source's timeline — both read 1 — and nothing in the WAL file names would tell the two apart.",
          usedIn: ['cnpg-basebackup-clone'],
        },
        {
          id: 'clone-credentials',
          kind: 'command',
          front: "Does the source's application password work on the clone?",
          back: "No. The role arrives with it inside the copied data directory, and then the operator resets the application user to the clone's own generated Secret.",
          usedIn: ['cnpg-basebackup-clone'],
        },
      ],
    },

    {
      id: 'roles',
      title: 'Declarative roles and databases',
      blurb: 'Roles, passwords and databases the operator owns and keeps reconciled.',
      cards: [
        {
          id: 'managed-role-shape',
          kind: 'command',
          front: 'What does an entry in `spec.managed.roles` consist of?',
          back: 'A name, an `ensure` of `present` or `absent`, the attributes the role should carry, and optionally a `passwordSecret` naming a Kubernetes Secret.',
          usedIn: ['cnpg-managed-roles'],
        },
        {
          id: 'managed-role-secret-keys',
          kind: 'command',
          front: 'What must the Secret behind a managed role contain?',
          back: 'Both a `username` and a `password` key, with `username` equal to the role name — otherwise the operator declines to use it.',
          usedIn: ['cnpg-managed-roles'],
        },
        {
          id: 'managed-role-drift',
          kind: 'lecture',
          front: 'Somebody runs `ALTER ROLE analyst NOLOGIN` by hand. What does the operator do?',
          back: 'Nothing, and it goes on reporting the role as `reconciled`. It compares against what it last applied, not against what the database currently says.',
          usedIn: ['cnpg-managed-roles'],
        },
        {
          id: 'managed-role-reapply',
          kind: 'lecture',
          front: 'What makes the operator re-apply a managed role?',
          back: 'Any change to its entry in the spec. It then applies the whole entry again, not just the field you touched — which is also how out-of-band drift gets corrected.',
          usedIn: ['cnpg-managed-roles'],
        },
        {
          id: 'managed-roles-list-patch',
          kind: 'command',
          front: 'Why does a merge patch on `spec.managed.roles` need the whole entry?',
          back: 'It is a list, so a merge patch replaces it wholesale. An entry re-sent without its `login` or its `passwordSecret` loses them.',
          usedIn: ['cnpg-managed-roles'],
        },
        {
          id: 'managed-roles-status-buckets',
          kind: 'command',
          front: 'What do `reserved` and `not-managed` mean in `status.managedRolesStatus.byStatus`?',
          back: '`reserved` are the operator’s own roles — postgres, streaming_replica, the metrics exporter — which you may not manage. `not-managed` exists but nothing has declared it, which is where `app` sits.',
          usedIn: ['cnpg-managed-roles'],
        },
        {
          id: 'ensure-absent-refused',
          kind: 'lecture',
          front: 'What happens to `ensure: absent` on a role that still owns objects?',
          back: 'PostgreSQL refuses. The role moves to `pending-reconciliation` and the refusal appears in `cannotReconcile` — "could not perform DELETE on role analyst: 2 objects in database app" — while the cluster stays healthy.',
          usedIn: ['cnpg-managed-roles'],
        },
        {
          id: 'managed-roles-alert-on',
          kind: 'lecture',
          front: 'What should you alert on for managed roles, and why not the cluster phase?',
          back: '`status.managedRolesStatus.cannotReconcile`. This failure leaves the cluster perfectly healthy and the request quietly unfulfilled.',
          usedIn: ['cnpg-managed-roles'],
        },
        {
          id: 'reload-label',
          kind: 'lecture',
          front: 'You edit a managed role\'s password Secret and nothing happens. Why?',
          back: 'The Secret is not labelled `cnpg.io/reload: "true"`, so the operator never watches it. Unlabelled Secrets are read only when the spec naming them changes.',
          usedIn: ['cnpg-role-passwords'],
        },
        {
          id: 'reload-label-evidence',
          kind: 'command',
          front: 'Where can you see CloudNativePG using the reload label itself?',
          back: '`kubectl get secret pg-cluster-app --show-labels` — the operator\'s own generated Secret carries `cnpg.io/reload=true` alongside `cnpg.io/cluster` and `cnpg.io/userType`.',
          usedIn: ['cnpg-role-passwords'],
        },
        {
          id: 'password-status-versions',
          kind: 'command',
          front: 'How do you tell in one line whether a password rotation has actually landed?',
          back: 'Compare the Secret\'s `metadata.resourceVersion` with `status.managedRolesStatus.passwordStatus.<role>.resourceVersion`. If they differ, the operator has not applied it.',
          usedIn: ['cnpg-role-passwords'],
        },
        {
          id: 'rotate-with-stringdata',
          kind: 'command',
          front: 'How do you write a new password into a Secret without base64?',
          back: '`kubectl patch secret analyst-password -p \'{"stringData":{"password":"…"}}\'` — `stringData` is write-only and the API server encodes it into `data`.',
          usedIn: ['cnpg-role-passwords'],
        },
        {
          id: 'password-drift-fix',
          kind: 'lecture',
          front: 'Somebody changed a managed role\'s password with ALTER ROLE. How do you get the Secret back in charge?',
          back: 'Touch the Secret — an annotation is enough. Any change moves its resourceVersion, and the operator overwrites the database on its next poll. It never reverts SQL changes on its own.',
          usedIn: ['cnpg-role-passwords'],
        },
        {
          id: 'valid-until-message',
          kind: 'lecture',
          front: 'What does a client see when a managed role\'s validUntil has passed?',
          back: '`FATAL: password authentication failed for user "analyst"` — the same message as a wrong password. PostgreSQL never says "expired", and the role still reads `reconciled`.',
          usedIn: ['cnpg-role-passwords'],
        },
        {
          id: 'disable-password-rules',
          kind: 'command',
          front: 'What happens if you set both disablePassword and passwordSecret on a role?',
          back: 'The webhook refuses the Cluster: "This role both sets and disables a password". On its own, `disablePassword: true` leaves `rolpassword` NULL.',
          usedIn: ['cnpg-role-passwords'],
        },
        {
          id: 'disable-password-side-effects',
          kind: 'lecture',
          front: 'After disabling a role\'s password, what else changed?',
          back: '`rolvaliduntil` went back to `infinity` — the whole entry is re-applied, so a dropped field is reset — and `passwordStatus` kept only a transaction id, with no Secret to track.',
          usedIn: ['cnpg-role-passwords'],
        },
        {
          id: 'database-object-shape',
          kind: 'command',
          front: 'What does a Database resource need in its spec?',
          back: 'The Cluster that hosts it, the name it should have in PostgreSQL, and an owner. The object\'s name and the database\'s name are separate fields.',
          usedIn: ['cnpg-declarative-databases'],
        },
        {
          id: 'database-status-applied',
          kind: 'command',
          front: 'Where does a Database report whether it worked?',
          back: 'Its own status — `applied`, `observedGeneration`, and a `message` when it failed — surfaced by `kubectl get database` as the APPLIED and MESSAGE columns.',
          usedIn: ['cnpg-declarative-databases'],
        },
        {
          id: 'database-duplicate-claim',
          kind: 'lecture',
          front: 'Two Database objects name the same PostgreSQL database. What happens?',
          back: 'The apply succeeds and the operator refuses the newcomer in its own status: `"reporting" is already managed by object "reporting-db"`. The first object is untouched.',
          usedIn: ['cnpg-declarative-databases'],
        },
        {
          id: 'database-adoption',
          kind: 'lecture',
          front: 'What happens if you declare a Database for a database that already exists?',
          back: 'It is adopted — `applied: true`, data intact, no recreation. That is what makes the retain default useful after a namespace rebuild, and it works by name alone.',
          usedIn: ['cnpg-declarative-databases'],
        },
        {
          id: 'database-finalizer',
          kind: 'command',
          front: 'Why does a Database object carry the cnpg.io/deleteDatabase finalizer?',
          back: 'So deleting the object is not just a Kubernetes deletion: the operator gets to act on the PostgreSQL database first, according to `databaseReclaimPolicy`.',
          usedIn: ['cnpg-declarative-databases', 'cnpg-database-reclaim'],
        },
        {
          id: 'reclaim-vs-ensure',
          kind: 'lecture',
          front: 'What is the difference between ensure: absent and databaseReclaimPolicy: delete?',
          back: '`ensure` is whether the database exists while the object does — reversible. The reclaim policy only fires when the object is deleted, by which point there is nothing left to change your mind with.',
          usedIn: ['cnpg-database-reclaim'],
        },
        {
          id: 'reclaim-delete-blocks',
          kind: 'lecture',
          front: 'Why can deleting a delete-policy Database object hang?',
          back: 'PostgreSQL will not drop a database with a session on it, so the finalizer waits. There is no event, no message and no operator log line — only a deletionTimestamp and a command that does not return.',
          usedIn: ['cnpg-database-reclaim'],
        },
        {
          id: 'reclaim-default',
          kind: 'command',
          front: 'What is the default databaseReclaimPolicy, and why that one?',
          back: '`retain`. Objects get deleted by mistaken commands, namespace cleanups and reconcilers pruning what they no longer see in Git — none of which should drop a database.',
          usedIn: ['cnpg-declarative-databases', 'cnpg-database-reclaim'],
        },
      ],
    },

    {
      id: 'failover',
      title: 'Failover and switchover',
      blurb: 'Losing a primary on purpose, and how fast the endpoint follows.',
      cards: [
        {
          id: 'failover-vs-switchover',
          kind: 'lecture',
          front: 'Failover versus switchover — what is the difference?',
          back: 'A failover is the operator reacting to a primary that is gone. A switchover is a planned promotion you ask for, with the old primary demoted to a standby rather than lost.',
          usedIn: ['cnpg-failover', 'cnpg-switchover'],
        },
        {
          id: 'cnpg-promote',
          kind: 'command',
          front: 'How do you deliberately move the primary to a named instance?',
          back: '`kubectl cnpg promote pg-cluster pg-cluster-2`. The operator demotes the old primary and it rejoins as a standby.',
          usedIn: ['cnpg-switchover'],
        },
        {
          id: 'promotion-timestamps',
          kind: 'command',
          front: 'How do you measure how long a promotion really took, after the fact?',
          back: 'The gap between `.status.targetPrimaryTimestamp` (the operator decided) and `.status.currentPrimaryTimestamp` (it became primary) — both stamped server-side.',
          usedIn: ['cnpg-failover-endpoint-time', 'cnpg-switchover-endpoint-time'],
        },
        {
          id: 'endpoint-follows',
          kind: 'lecture',
          front: 'What actually redirects clients after a failover?',
          back: 'The `-rw` Service\'s endpoint changes to the new primary\'s Pod IP. Until it does, clients are still being sent to a database that cannot accept writes.',
          usedIn: ['cnpg-failover-endpoint-time'],
        },
        {
          id: 'degraded-not-failed',
          kind: 'lecture',
          front: 'A cluster loses a replica. Why is that not a failover?',
          back: 'Degraded is not failed — there is still a primary, it takes writes, and the `-rw` Service never moves. A lost replica only needs replacing; only a lost primary demands a promotion.',
          usedIn: ['cnpg-degraded-recovery'],
        },
      ],
    },

    {
      id: 'backup',
      title: 'Backup and recovery',
      blurb: 'Object storage, volume snapshots and point-in-time recovery.',
      cards: [
        {
          id: 'barman-plugin-not-in-tree',
          kind: 'lecture',
          front: 'Why do these labs use the Barman Cloud *plugin* rather than `spec.backup.barmanObjectStore`?',
          back: 'The in-tree field still exists in 1.30 but warns on every use and is removed in 1.31. The plugin is the supported path.',
          usedIn: ['cnpg-barman-backup'],
        },
        {
          id: 'pitr-target',
          kind: 'command',
          front: 'How do you recover a cluster to a specific moment rather than to the latest WAL?',
          back: 'Bootstrap with `recovery` and a `recoveryTarget` — `targetTime` for a timestamp. The new cluster replays the archive up to that point and stops.',
          usedIn: ['cnpg-pitr'],
        },
        {
          id: 'wal-maxparallel',
          kind: 'lecture',
          front: 'What does `wal.maxParallel` change during a restore?',
          back: 'How many WAL segments are fetched at once. Measured here: three sequential recoveries took 81, 72 and 91 seconds against 61, 56 and 60 with `maxParallel: 8`.',
          usedIn: ['cnpg-wal-restore'],
        },
        {
          id: 'snapshot-needs-csi',
          kind: 'lecture',
          front: 'Why can\'t volume-snapshot backups work on a default k3s cluster?',
          back: 'Its `local-path` storage class cannot snapshot. Snapshots need a CSI driver that supports them, plus the external-snapshotter CRDs.',
          usedIn: ['cnpg-volume-snapshots'],
        },
        {
          id: 'restore-is-a-new-cluster',
          kind: 'lecture',
          front: 'Does CloudNativePG restore into an existing cluster?',
          back: 'No. Recovery is a *bootstrap method* — a new Cluster whose `bootstrap` says `recovery` instead of `initdb`. The original keeps running untouched, so you end with a second database with its own Services and credentials.',
          usedIn: ['cnpg-barman-restore'],
        },
        {
          id: 'servername-routes-recovery',
          kind: 'command',
          front: "One bucket holds several clusters' backups. What makes a recovery read the right one?",
          back: '`serverName` in the `externalClusters` entry, alongside the Barman plugin and the ObjectStore to read from.',
          usedIn: ['cnpg-barman-restore', 'cnpg-replica-from-backup'],
        },
        {
          id: 'replica-enabled-turns-restore',
          kind: 'command',
          front: 'Which single field turns a restore-from-backup into a replica instead of a new primary?',
          back: '`replica.enabled`. Without it the recovered cluster promotes itself onto its own timeline; with it, it stays in recovery and keeps replaying whatever the source archives.',
          usedIn: ['cnpg-replica-from-backup'],
        },
        {
          id: 'archive-replica-no-receiver',
          kind: 'command',
          front: 'How can you tell a replica is fed by an archive rather than by streaming?',
          back: 'It has no WAL receiver: `pg_last_wal_receive_lsn` stays empty while `pg_last_wal_replay_lsn` advances — and the source\'s `pg_stat_replication` never lists it at all.',
          usedIn: ['cnpg-replica-from-backup'],
        },
        {
          id: 'archive-replica-latency',
          kind: 'lecture',
          front: 'Why does a row take longer to reach an archive-fed replica than a streaming one?',
          back: 'Its latency is a whole WAL segment: nothing arrives until the segment carrying it is archived. `SELECT pg_switch_wal()` on the primary forces that immediately.',
          usedIn: ['cnpg-replica-from-backup'],
        },
        {
          id: 'snapshot-ready-to-use',
          kind: 'command',
          front: "What says a VolumeSnapshot's copy exists, rather than just the request for it?",
          back: '`status.readyToUse`. Behind it sits a cluster-scoped `VolumeSnapshotContent` representing the actual snapshot in the storage system.',
          usedIn: ['cnpg-replica-from-snapshot'],
        },
        {
          id: 'snapshot-crash-consistent',
          kind: 'lecture',
          front: 'Nothing quiesces the database before a volume snapshot. Why is the copy usable?',
          back: 'It is crash-consistent, exactly like pulling the power — which is fine, because recovering from a crash is what PostgreSQL does on every start.',
          usedIn: ['cnpg-replica-from-snapshot', 'cnpg-volume-snapshots'],
        },
        {
          id: 'snapshot-seed-then-stream',
          kind: 'lecture',
          front: 'A snapshot is a moment, not a stream. What has to pair with it to make a replica?',
          back: '`replica.enabled` plus a streaming `externalClusters` entry: the snapshot is the seed, streaming keeps it current. Unlike an archive-fed replica, this one has a WAL receiver.',
          usedIn: ['cnpg-replica-from-snapshot'],
        },
        {
          id: 'snapshot-online-default',
          kind: 'command',
          front: "What does `spec.online: false` change about a volumeSnapshot backup?",
          back: "The operator fences the target instance first, so the snapshot is of a cleanly shut down data directory rather than a running one. The default is true.",
          usedIn: ['cnpg-snapshot-modes'],
        },
        {
          id: 'snapshot-backup-label',
          kind: 'lecture',
          front: "Which annotation tells you a snapshot was taken online?",
          back: "`cnpg.io/backupLabelFile` — base64 of PostgreSQL's own backup_label, recording where recovery must begin. A cold snapshot has none, because nothing was running to label.",
          usedIn: ['cnpg-snapshot-modes'],
        },
        {
          id: 'snapshot-controldata',
          kind: 'command',
          front: "Where is the difference between a hot and a cold snapshot recorded?",
          back: "In the snapshot's `cnpg.io/pgControldata` annotation: `Database cluster state: in production` against `shut down`.",
          usedIn: ['cnpg-snapshot-modes'],
        },
        {
          id: 'snapshot-status-online',
          kind: 'lecture',
          front: "Which field says how a volumeSnapshot backup was actually taken?",
          back: "`.spec.online` — what was asked for. In this operator release `.status.online` reported true even for a backup taken with online false.",
          usedIn: ['cnpg-snapshot-modes'],
        },
        {
          id: 'snapshot-pitr-two-halves',
          kind: 'lecture',
          front: 'What does a volume snapshot supply in a point-in-time recovery, and what supplies the rest?',
          back: 'The snapshot supplies the data directory — the floor recovery starts from. The WAL archive, reached through an `externalClusters` entry, supplies everything committed after it.',
          usedIn: ['cnpg-snapshot-pitr'],
        },
        {
          id: 'snapshot-pitr-three-fields',
          kind: 'command',
          front: 'Which three parts of a recovery manifest make PITR from a snapshot work?',
          back: '`bootstrap.recovery.volumeSnapshots` (where the data comes from), `bootstrap.recovery.source` naming an `externalClusters` entry (where the WAL comes from), and `recoveryTarget.targetTime` (where to stop).',
          usedIn: ['cnpg-snapshot-pitr'],
        },
        {
          id: 'pitr-target-clock',
          kind: 'lecture',
          front: 'Whose clock should a recovery target time come from?',
          back: "The database's — `SELECT now()`. A node's clock is a different one, and recovery compares the target against the transaction log.",
          usedIn: ['cnpg-snapshot-pitr'],
        },
        {
          id: 'hot-cold-recover-same',
          kind: 'lecture',
          front: 'Does recovering from a cold snapshot reach a different point in time than from a hot one?',
          back: 'No. Aimed at the same `targetTime` both land on the same row. The mode decides what happens when the copy is opened; how far forward you can go is the archive’s job.',
          usedIn: ['cnpg-snapshot-pitr'],
        },
        {
          id: 'pitr-datasource-proof',
          kind: 'command',
          front: 'How do you prove which snapshot a recovered cluster was built from?',
          back: '`kubectl get pvc <cluster>-1 -o jsonpath=\'{.spec.dataSource}\'` — it names the VolumeSnapshot. An ordinary claim has no dataSource.',
          usedIn: ['cnpg-snapshot-pitr', 'cnpg-volume-snapshots'],
        },
        {
          id: 'backups-serialize',
          kind: 'lecture',
          front: 'What happens if you apply two Backups to the same cluster at once?',
          back: 'They serialize — the second sits in `pending` until the first finishes, then goes to `started`.',
          usedIn: ['cnpg-snapshot-pitr'],
        },
        {
          id: 'cnpg-backup-builds-object',
          kind: 'lecture',
          front: 'What does `kubectl cnpg backup` actually do?',
          back: 'It builds an ordinary Backup resource out of its flags and applies it. The operator then does exactly what it would have done for a hand-written manifest.',
          usedIn: ['cnpg-plugin-snapshot-backup'],
        },
        {
          id: 'plugin-backup-default-name',
          kind: 'command',
          front: 'What name does the plugin choose when you do not pass `--backup-name`?',
          back: 'The cluster name and a timestamp — `pg-cluster-20260817015306`. Unambiguous, and unmemorable when you need to find it under pressure.',
          usedIn: ['cnpg-plugin-snapshot-backup'],
        },
        {
          id: 'plugin-online-unset',
          kind: 'command',
          front: 'A backup listing shows `ONLINE` as `<none>` — what does that mean?',
          back: '`spec.online` was never set, so the Cluster’s `spec.backup.volumeSnapshot.online` decides. An explicit `false` and an empty field can agree today and differ tomorrow.',
          usedIn: ['cnpg-plugin-snapshot-backup'],
        },
        {
          id: 'plugin-online-flag-form',
          kind: 'command',
          front: 'How do you ask the plugin for an offline backup?',
          back: '`--online=false`. It takes a value rather than being a switch; accepted values are `true|false|""`.',
          usedIn: ['cnpg-plugin-snapshot-backup'],
        },
        {
          id: 'last-successful-by-method',
          kind: 'command',
          front: 'Which cluster status field stops you misreading a recoverability point?',
          back: '`status.lastSuccessfulBackupByMethod`. A first point of recoverability means little until you know which method produced it.',
          usedIn: ['cnpg-plugin-snapshot-backup'],
        },
        {
          id: 'scheduled-six-fields',
          kind: 'command',
          front: 'How many fields does a ScheduledBackup schedule have?',
          back: 'Six — CloudNativePG counts seconds first. `"0 * * * * *"` is second zero of every minute, not what the same string means in a crontab.',
          usedIn: ['cnpg-scheduled-snapshots'],
        },
        {
          id: 'scheduled-status-times',
          kind: 'command',
          front: 'Which ScheduledBackup field should monitoring watch?',
          back: '`status.lastScheduleTime`. If it stops moving, backups have stopped happening and nothing else in the cluster will say so.',
          usedIn: ['cnpg-scheduled-snapshots'],
        },
        {
          id: 'scheduled-suspend',
          kind: 'command',
          front: 'How do you stop a schedule for a maintenance window without losing it?',
          back: '`spec.suspend: true` — it stops the clock without deleting the schedule or anything it has made.',
          usedIn: ['cnpg-scheduled-snapshots'],
        },
        {
          id: 'scheduled-immediate',
          kind: 'command',
          front: 'What does `immediate: true` on a ScheduledBackup do, and why use it?',
          back: 'It fires the schedule once at creation. A schedule that has never run is a schedule nobody has tested.',
          usedIn: ['cnpg-scheduled-snapshots'],
        },
        {
          id: 'nothing-prunes-snapshots',
          kind: 'lecture',
          front: 'What deletes old VolumeSnapshots?',
          back: 'Nothing. Retention policies belong to Barman and apply to an object store; a VolumeSnapshot is a Kubernetes object the CSI driver made, and CloudNativePG does not prune them.',
          usedIn: ['cnpg-scheduled-snapshots'],
        },
        {
          id: 'snapshot-owner-reference-card',
          kind: 'command',
          front: 'Which field decides whether deleting a Backup deletes its snapshot?',
          back: '`spec.backup.volumeSnapshot.snapshotOwnerReference`. It defaults to `none`, so the snapshot survives; `backup` gives it an ownerReference and it is garbage-collected with the Backup. The third value is `cluster`.',
          usedIn: ['cnpg-scheduled-snapshots'],
        },
        {
          id: 'tablespace-recovery-must-declare',
          kind: 'lecture',
          front: 'What does a recovery manifest need if the backup came from a cluster with tablespaces?',
          back: 'A `tablespaces` block naming the same tablespaces. Without it the restore has nowhere to unpack them and fails with `[Errno 30] Read-only file system: \'/var/lib/postgresql/tablespaces\'`.',
          usedIn: ['cnpg-tablespace-backup'],
        },
        {
          id: 'tablespace-recovery-symptom',
          kind: 'command',
          front: 'A recovery sits at "Setting up primary" forever. Where is the reason?',
          back: 'In the logs of the `<cluster>-1-full-recovery-…` Job Pods, which fail and are replaced. Pick one in Error — the Cluster\'s own status never says why.',
          usedIn: ['cnpg-tablespace-backup'],
        },
        {
          id: 'backup-first-wal',
          kind: 'command',
          front: 'Why can a completed base backup still be unrestorable?',
          back: 'Recovery needs the whole WAL segment the backup begins in — `status.beginWal` — and an idle database never closes it. `SELECT pg_switch_wal()` after the backup fixes it.',
          usedIn: ['cnpg-tablespace-backup'],
        },
        {
          id: 'snapshot-per-volume',
          kind: 'command',
          front: 'How many VolumeSnapshots does a snapshot backup of a cluster with one tablespace produce?',
          back: 'Two: `<backup>` from the data claim and `<backup>-tbs-<tablespace>` from the tablespace claim, the second labelled `cnpg.io/tablespaceName`.',
          usedIn: ['cnpg-tablespace-snapshot'],
        },
        {
          id: 'tablespace-storage-map',
          kind: 'command',
          front: 'Which field maps a tablespace back to its snapshot during recovery?',
          back: '`bootstrap.recovery.volumeSnapshots.tablespaceStorage`, keyed by tablespace name. `storage` covers the data directory only.',
          usedIn: ['cnpg-tablespace-snapshot'],
        },
        {
          id: 'missing-storage-source',
          kind: 'lecture',
          front: 'A snapshot recovery creates one Pending claim, no Pod and no events. What is wrong?',
          back: 'A tablespace has no snapshot mapped. The reason exists only in the operator log: `cannot create primary instance PVCs: missing StorageSource for tablespace <name> PVC`.',
          usedIn: ['cnpg-tablespace-snapshot'],
        },
        {
          id: 'tbs-in-cluster-name',
          kind: 'lecture',
          front: 'Why must a cluster with tablespaces not have "-tbs-" in its name?',
          back: 'A tablespace claim is `<instance>-tbs-<tablespace>`, so the operator reads the cluster\'s own data claim as a tablespace\'s and rolls the instance forever — data intact, cluster never ready.',
          usedIn: ['cnpg-tablespace-snapshot'],
        },
        {
          id: 'schedules-collide',
          kind: 'lecture',
          front: 'Two schedules both fire at second zero. What can go wrong?',
          back: 'They contend for the same cluster. An online run landing while a cold one has the instance fenced fails — "while ensuring target pod is healthy: no status found for target pod". Stagger the seconds.',
          usedIn: ['cnpg-scheduled-snapshots'],
        },
        {
          id: 'cold-schedule-cost',
          kind: 'lecture',
          front: 'What does an `online: false` schedule cost on a single-instance cluster?',
          back: 'A small outage on every run — the instance is fenced while the snapshot is taken, and on a one-instance cluster that instance is the database.',
          usedIn: ['cnpg-scheduled-snapshots'],
        },
      ],
    },

    {
      id: 'observability',
      title: 'Metrics and logs',
      blurb: 'What every instance already exports, and the shape of its logs.',
      cards: [
        {
          id: 'metrics-port',
          kind: 'command',
          front: 'Which ports serve Prometheus metrics for an instance and for a pooler?',
          back: '9187 for a database instance, 9127 for a PgBouncer Pod. A scrape config that assumes one silently misses the other.',
          usedIn: ['cnpg-metrics', 'cnpg-pgbouncer-metrics'],
        },
        {
          id: 'collector-up-first',
          kind: 'lecture',
          front: 'Which metric should you alert on before any of the others?',
          back: '`cnpg_collector_up`. A dashboard full of stale values with `collector_up 0` behind it is the classic misleading monitoring failure.',
          usedIn: ['cnpg-metrics'],
        },
        {
          id: 'custom-query-metric',
          kind: 'command',
          front: 'How do you export a metric about *your* data rather than about PostgreSQL?',
          back: 'SQL in a ConfigMap referenced by `spec.monitoring.customQueriesConfigMap`. The family name and column become `cnpg_<family>_<column>`.',
          usedIn: ['cnpg-metrics'],
        },
        {
          id: 'json-logs-default',
          kind: 'lecture',
          front: 'What log format does CloudNativePG use, and what can you switch it to?',
          back: 'Structured JSON, always — there is no plain-text mode. PostgreSQL\'s own CSV log fields arrive nested under a `record` key.',
          usedIn: ['cnpg-json-logs'],
        },
        {
          id: 'find-by-sqlstate',
          kind: 'command',
          front: 'Why search logs by `sql_state_code` rather than by the error message?',
          back: 'It is a stable five-character code, so it finds that class of failure regardless of message wording or locale. Division by zero is `22012`.',
          usedIn: ['cnpg-json-logs'],
        },
        {
          id: 'logs-cluster-aggregate',
          kind: 'command',
          front: 'How do you read every instance\'s log as one stream?',
          back: '`kubectl cnpg logs cluster pg-cluster`, tagged per Pod by `logging_pod`. `-f` follows Pods created while it runs, which is what makes it usable during a failover.',
          usedIn: ['cnpg-json-logs'],
        },
      ],
    },
  ],
}
